"""Type stubs for Infernux.components package."""

from __future__ import annotations

from typing import Callable, List, Optional, Tuple, Type, TypeVar

_SerializedValue = TypeVar("_SerializedValue")

from .component import InxComponent as InxComponent
from .builtin_component import BuiltinComponent, CppProperty
from .builtin import (
    Light as Light,
    MeshRenderer as MeshRenderer,
    LineRenderer as LineRenderer,
    SkinnedMeshRenderer as SkinnedMeshRenderer,
    Camera as Camera,
    Collider as Collider,
    BoxCollider as BoxCollider,
    SphereCollider as SphereCollider,
    CapsuleCollider as CapsuleCollider,
    CylinderCollider as CylinderCollider,
    MeshCollider as MeshCollider,
    Rigidbody as Rigidbody,
    RigidbodyConstraints as RigidbodyConstraints,
    CollisionDetectionMode as CollisionDetectionMode,
    RigidbodyInterpolation as RigidbodyInterpolation,
    HingeJoint as HingeJoint,
    SliderJoint as SliderJoint,
    AudioSource as AudioSource,
    AudioListener as AudioListener,
    SpriteRenderer as SpriteRenderer,
)
from Infernux.lib._Infernux import Transform as Transform, Component as Component
from .serializable_object import SerializableObject as SerializableObject
from .value_codec import (
    ValueCodecDescriptor as ValueCodecDescriptor,
    ValueCodecRegistry as ValueCodecRegistry,
    VALUE_CODECS as VALUE_CODECS,
)
from .fields import (
    int_field as int_field,
    list_field as list_field,
    component_field as component_field,
    component_list_field as component_list_field,
    hide_field as hide_field,
    FieldType as FieldType,
    get_serialized_fields as get_serialized_fields,
    get_field_value as get_field_value,
    set_field_value as set_field_value,
    Range as Range,
    Tooltip as Tooltip,
    Header as Header,
    Space as Space,
    Group as Group,
    InfoText as InfoText,
    DragSpeed as DragSpeed,
    RequiredComponent as RequiredComponent,
    FormerlySerializedAs as FormerlySerializedAs,
    Multiline as Multiline,
    ReadOnly as ReadOnly,
    HideInInspector as HideInInspector,
    NonSerialized as NonSerialized,
    HDR as HDR,
    Color as Color,
)
from Infernux.graph.ramp import (
    AnimationCurve as AnimationCurve,
    Gradient as Gradient,
    GradientKey as GradientKey,
    Keyframe as Keyframe,
)


def serialized_field(
    default: _SerializedValue = ...,
    *,
    field_type: Optional[FieldType] = ...,
    element_type: Optional[FieldType] = ...,
    element_class: Optional[Type] = ...,
    serializable_class: Optional[Type] = ...,
    component_type: Optional[str] = ...,
    asset_type: Optional[str] = ...,
    range: Optional[Tuple[float, float]] = ...,
    tooltip: str = ...,
    display_name_key: str = ...,
    enum_labels: Optional[List[str]] = ...,
    readonly: bool = ...,
    header: str = ...,
    space: float = ...,
    group: str = ...,
    info_text: str = ...,
    multiline: bool = ...,
    slider: bool = ...,
    drag_speed: Optional[float] = ...,
    required_component: Optional[str] = ...,
    visible_when: Optional[Callable] = ...,
    hdr: bool = ...,
    curve_non_negative: bool = ...,
    hidden: bool = ...,
) -> _SerializedValue: ...
InspectorSpace = Space
from .ref_wrappers import (
    GameObjectRef as GameObjectRef,
    MaterialRef as MaterialRef,
    ComponentRef as ComponentRef,
    PrefabRef as PrefabRef,
)
from .script_loader import (
    load_component_from_file as load_component_from_file,
    load_all_components_from_file as load_all_components_from_file,
    create_component_instance as create_component_instance,
    load_and_create_component as load_and_create_component,
    get_component_info as get_component_info,
    ScriptLoadError as ScriptLoadError,
)
from .spirit_animator import SpiritAnimator as SpiritAnimator
from .skeletal_animator import SkeletalAnimator as SkeletalAnimator
from .timeline_action import TimelineAction as TimelineAction
from .particle_system import ParticleBoundsMode as ParticleBoundsMode, ParticleOffscreenPolicy as ParticleOffscreenPolicy, ParticleSystem as ParticleSystem
from .runtime_acceptance_runner import RuntimeAcceptanceRunner as RuntimeAcceptanceRunner
from .registry import (
    get_type as get_type,
    get_all_types as get_all_types,
    T as T,
)
from .decorators import (
    require_component as require_component,
    disallow_multiple as disallow_multiple,
    execute_in_edit_mode as execute_in_edit_mode,
    add_component_menu as add_component_menu,
    icon as icon,
    help_url as help_url,
    RequireComponent as RequireComponent,
    DisallowMultipleComponent as DisallowMultipleComponent,
    ExecuteInEditMode as ExecuteInEditMode,
    AddComponentMenu as AddComponentMenu,
    HelpURL as HelpURL,
    Icon as Icon,
)

__all__ = [
    "InxComponent",
    "Component",
    "Transform",
    "Light",
    "MeshRenderer",
    "LineRenderer",
    "SkinnedMeshRenderer",
    "Camera",
    "Collider",
    "BoxCollider",
    "SphereCollider",
    "CapsuleCollider",
    "CylinderCollider",
    "MeshCollider",
    "Rigidbody",
    "RigidbodyConstraints",
    "CollisionDetectionMode",
    "RigidbodyInterpolation",
    "HingeJoint",
    "SliderJoint",
    "AudioSource",
    "AudioListener",
    "SpriteRenderer",
    "serialized_field",
    "int_field",
    "hide_field",
    "FieldType",
    "Range",
    "Tooltip",
    "Header",
    "InspectorSpace",
    "Group",
    "InfoText",
    "DragSpeed",
    "RequiredComponent",
    "FormerlySerializedAs",
    "Multiline",
    "ReadOnly",
    "HideInInspector",
    "NonSerialized",
    "HDR",
    "Color",
    "AnimationCurve",
    "Keyframe",
    "Gradient",
    "GradientKey",
    "GameObjectRef",
    "MaterialRef",
    "ComponentRef",
    "PrefabRef",
    "SerializableObject",
    "ValueCodecDescriptor",
    "ValueCodecRegistry",
    "VALUE_CODECS",
    "list_field",
    "component_field",
    "component_list_field",
    "get_serialized_fields",
    "get_field_value",
    "set_field_value",
    "load_component_from_file",
    "load_all_components_from_file",
    "create_component_instance",
    "load_and_create_component",
    "get_component_info",
    "ScriptLoadError",
    "get_type",
    "get_all_types",
    "T",
    "require_component",
    "disallow_multiple",
    "execute_in_edit_mode",
    "add_component_menu",
    "icon",
    "help_url",
    "RequireComponent",
    "DisallowMultipleComponent",
    "ExecuteInEditMode",
    "AddComponentMenu",
    "HelpURL",
    "Icon",
    "SpiritAnimator",
    "SkeletalAnimator",
    "TimelineAction",
    "ParticleSystem",
    "ParticleBoundsMode",
    "ParticleOffscreenPolicy",
    "RuntimeAcceptanceRunner",
]
