from __future__ import annotations

from typing import Optional

from Infernux.components.component import InxComponent
from Infernux.core.anim_state_machine import AnimStateMachine

class SpiritAnimator(InxComponent):
    """Drives a SpriteRenderer from a 2D AnimStateMachine asset."""

    # SerializedField resolves ASSET refs to the loaded object when possible.
    controller: Optional[AnimStateMachine]
    playback_speed: float
    auto_play: bool

    def awake(self) -> None: ...
    def start(self) -> None: ...
    def update(self, delta_time: float) -> None: ...

    @property
    def current_state(self) -> str: ...
    @property
    def is_playing(self) -> bool: ...
    @property
    def normalized_time(self) -> float: ...

    def play(self, state_name: str = ...) -> bool: ...
    def stop(self) -> None: ...

    def set_parameter(self, name: str, value: object) -> None: ...
    def get_parameter(self, name: str, default: object = ...) -> object: ...

    def get_bool(self, name: str) -> bool: ...
    def set_bool(self, name: str, value: bool) -> None: ...

    def get_float(self, name: str) -> float: ...
    def set_float(self, name: str, value: float) -> None: ...

    def get_int(self, name: str) -> int: ...
    def set_int(self, name: str, value: int) -> None: ...

    def set_trigger(self, name: str) -> None: ...

    def reload_controller(self) -> None: ...

    def on_after_deserialize(self) -> None: ...
