from infernux.components.component import InxComponent
from infernux.core.asset_ref import ParticleGraphRef
from infernux.lib import Vector3
from infernux.particle import ParticleRuntimeCompatibility
from infernux.graph.ramp import AnimationCurve, Gradient
from enum import Enum

class ParticleBoundsMode(str, Enum):
    AUTOMATIC: ParticleBoundsMode
    MANUAL: ParticleBoundsMode

class ParticleOffscreenPolicy(str, Enum):
    ALWAYS_SIMULATE: ParticleOffscreenPolicy
    PAUSE_WHEN_OFFSCREEN: ParticleOffscreenPolicy

class ParticleSystem(InxComponent):
    graph: ParticleGraphRef
    simulation_speed: float
    play_on_awake: bool
    random_seed: int
    prewarm: bool
    offscreen_policy: ParticleOffscreenPolicy
    bounds_mode: ParticleBoundsMode
    manual_bounds_center: Vector3
    manual_bounds_size: Vector3
    @property
    def is_resident(self) -> bool: ...
    @property
    def is_playing(self) -> bool: ...
    @property
    def time(self) -> float: ...
    @property
    def last_compile_error(self) -> str: ...
    def has_parameter(self, name: str) -> bool: ...
    def exposed_parameter_schema(self) -> list[dict]: ...
    def emitter_instance_schema(self) -> list[dict]: ...
    def set_emitter_options(
        self,
        emitter: int | str,
        *,
        enabled: bool | None = ...,
        play_on_start: bool | None = ...,
    ) -> bool: ...
    def set_parameter(self, name: str, value) -> None: ...
    def get_parameter(self, name: str): ...
    def reset_parameter(self, name: str) -> bool: ...
    def set_texture(self, name: str, value) -> None: ...
    def get_texture(self, name: str): ...
    def set_curve(self, name: str, value: AnimationCurve | dict) -> None: ...
    def get_curve(self, name: str) -> AnimationCurve: ...
    def set_gradient(self, name: str, value: Gradient | dict) -> None: ...
    def get_gradient(self, name: str) -> Gradient: ...
    def set_bool(self, name: str, value: bool) -> None: ...
    def get_bool(self, name: str, default: bool = ...) -> bool: ...
    def set_int(self, name: str, value: int) -> None: ...
    def get_int(self, name: str, default: int = ...) -> int: ...
    def set_uint(self, name: str, value: int) -> None: ...
    def get_uint(self, name: str, default: int = ...) -> int: ...
    def set_float(self, name: str, value: float) -> None: ...
    def get_float(self, name: str, default: float = ...) -> float: ...
    def set_vector2(self, name: str, x: float, y: float) -> None: ...
    def get_vector2(self, name: str) -> tuple[float, float]: ...
    def set_vector3(self, name: str, x: float, y: float, z: float) -> None: ...
    def get_vector3(self, name: str) -> tuple[float, float, float]: ...
    def set_vector4(self, name: str, x: float, y: float, z: float, w: float) -> None: ...
    def get_vector4(self, name: str) -> tuple[float, float, float, float]: ...
    def set_color(self, name: str, r: float, g: float, b: float, a: float = ...) -> None: ...
    def get_color(self, name: str) -> tuple[float, float, float, float]: ...
    def runtime_event_schema(self) -> list[dict]: ...
    def runtime_diagnostics(self) -> dict: ...
    def request_gpu_diagnostics(self, sample_frames: int = 60, state_sample_count: int = 0) -> int: ...
    def poll_gpu_diagnostics(self, request_id: int) -> dict: ...
    def request_gpu_view_diagnostics(self, view: str, camera_component_id: int = ...) -> int: ...
    def poll_gpu_view_diagnostics(self, view: str, request_id: int, camera_component_id: int = ...) -> dict: ...
    def play(self, emitter: int | str | None = None) -> bool: ...
    def pause(self, emitter: int | str | None = None) -> bool: ...
    def stop(self, emitter: int | str | None = None) -> bool: ...
    def restart(self, emitter: int | str | None = None, *, honor_play_on_start: bool = False) -> bool: ...
    def seek(self, time_seconds: float, emitter: int | str | None = None) -> bool: ...
    def reset_simulation(self, emitter: int | str | None = None) -> bool: ...
    def start_emitter(self, emitter: int | str) -> bool: ...
    def pause_emitter(self, emitter: int | str) -> bool: ...
    def terminate_emitter(self, emitter: int | str) -> bool: ...
    def emitter_reload_compatibility(self, emitter_index: int) -> ParticleRuntimeCompatibility | None: ...
    def editor_preview_begin(self) -> bool: ...
    def editor_preview_update(self, delta_time: float, speed: float = 1.0) -> bool: ...
    def editor_preview_play(self) -> bool: ...
    def editor_preview_pause(self) -> bool: ...
    def editor_preview_suspend(self) -> bool: ...
    def editor_preview_is_playing(self) -> bool: ...
    def editor_preview_is_ready(self) -> bool: ...
    def editor_preview_stop(self) -> bool: ...
    def editor_preview_set_emitter_muted(self, emitter_index: int, muted: bool) -> bool: ...
    def editor_preview_set_emitter_solo(self, emitter_index: int, solo: bool) -> bool: ...
    def editor_preview_restart_emitter(self, emitter_index: int) -> bool: ...
    def editor_preview_emitter_states(self) -> list[dict]: ...
    def editor_preview_end(self) -> None: ...
