from __future__ import annotations

from typing import Dict, Optional, Set, Type


def invalidate_discovery_cache(source_path: str | None = None) -> None: ...
def discover_pipelines() -> Dict[str, type]: ...
def discover_passes() -> Dict[str, type]: ...
def discovery_import_failures() -> Dict[str, str]: ...
def discovery_name_conflicts(kind: str = "pipeline") -> dict[str, tuple[str, ...]]: ...
