from enum import Enum
from typing import Iterable, Optional
from infernux.renderstack.effect_stage import EffectScope

MATERIAL_QUEUE_MIN: int
MATERIAL_QUEUE_MAX: int
OPAQUE_QUEUE: tuple[int, int]
TRANSPARENT_QUEUE: tuple[int, int]

class Path(str, Enum):
    FORWARD: str
    FORWARD_PLUS: str
    DEFERRED: str

class Queue:
    minimum: int
    maximum: int
    def __init__(self, minimum: int, maximum: Optional[int] = ...) -> None: ...
    @classmethod
    def exact(cls, value: int) -> Queue: ...
    @classmethod
    def range(cls, minimum: int, maximum: int) -> Queue: ...
    @classmethod
    def named(cls, name: str) -> Queue: ...
    @classmethod
    def all_opaque(cls) -> Queue: ...
    @classmethod
    def all_transparent(cls) -> Queue: ...
    def contains(self, other: Queue) -> bool: ...
    def overlaps(self, other: Queue) -> bool: ...
    def as_tuple(self) -> tuple[int, int]: ...

QueueSelector = Queue

class EffectStageDefinition:
    stable_id: str
    scope: EffectScope
    owner_id: str
    display_name: str

class RouteDefinition:
    route_id: str
    domain: str
    selector: Optional[Queue]
    path: Path
    fallback: Optional[Path]
    layer_id: str
    is_otherwise: bool
    effects: list[EffectStageDefinition]

class LayerDefinition:
    layer_id: str
    display_name: str
    routes: list[RouteDefinition]
    effects: list[EffectStageDefinition]
    operations: list[tuple[str, str]]

class DomainDefinition:
    domain_id: str
    queue: Queue
    routes: list[RouteDefinition]
    layers: list[LayerDefinition]
    effects: list[EffectStageDefinition]
    operations: list[tuple[str, str]]
    def all_routes(self) -> tuple[RouteDefinition, ...]: ...

class PipelineDefinition:
    domains: list[DomainDefinition]
    effect_order: list[EffectStageDefinition]
    operations: list[tuple[str, str]]
    has_sky: bool
    has_screen_ui: bool
    @property
    def effect_stages(self) -> tuple[EffectStageDefinition, ...]: ...
    def domain(self, domain_id: str) -> DomainDefinition: ...

class QueueRoute:
    route_id: str
    selector: Queue
    def __init__(self, route_id: str, selector: Queue) -> None: ...

class QueueSegment:
    selector: Queue
    route_id: Optional[str]
    is_otherwise: bool

def compile_queue_segments(
    base: Queue,
    routes: Iterable[QueueRoute | RouteDefinition],
    *,
    include_otherwise: bool,
) -> tuple[QueueSegment, ...]: ...

class PipelineBuilder:
    definition: PipelineDefinition
    def __init__(self) -> None: ...
    def frame(self, *, hdr: bool = ..., msaa: int = ...) -> PipelineBuilder: ...
    def shadows(self, *, resolution: int = ...) -> PipelineBuilder: ...
    def lighting(self, *, clustered: bool = ...) -> PipelineBuilder: ...
    def opaque(self) -> DomainBuilder: ...
    def transparent(self) -> DomainBuilder: ...
    def sky(self) -> PipelineBuilder: ...
    def effects(self, stable_id: str, *, label: str = ...) -> EffectStageDefinition: ...
    def screen_ui(self) -> PipelineBuilder: ...
    def build(self) -> PipelineDefinition: ...

class DomainBuilder:
    def __enter__(self) -> DomainBuilder: ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...
    def layer(self, name: str) -> LayerBuilder: ...
    def forward(self, selector: Optional[Queue] = ...) -> RouteBuilder: ...
    def forward_plus(self, selector: Optional[Queue] = ...) -> RouteBuilder: ...
    def deferred(self, selector: Optional[Queue] = ..., *, fallback: Optional[Path] = ...) -> RouteBuilder: ...
    def otherwise(self) -> OtherwiseBuilder: ...
    def effects(self, stable_id: str, *, label: str = ...) -> EffectStageDefinition: ...

class LayerBuilder:
    def __enter__(self) -> LayerBuilder: ...
    def __exit__(self, exc_type, exc, tb) -> bool: ...
    def forward(self, selector: Optional[Queue] = ...) -> RouteBuilder: ...
    def forward_plus(self, selector: Optional[Queue] = ...) -> RouteBuilder: ...
    def deferred(self, selector: Optional[Queue] = ..., *, fallback: Optional[Path] = ...) -> RouteBuilder: ...
    def otherwise(self) -> OtherwiseBuilder: ...
    def effects(self, stable_id: str, *, label: str = ...) -> EffectStageDefinition: ...

class OtherwiseBuilder:
    def forward(self) -> RouteBuilder: ...
    def forward_plus(self) -> RouteBuilder: ...
    def deferred(self, *, fallback: Optional[Path] = ...) -> RouteBuilder: ...

class RouteBuilder:
    route: RouteDefinition
    def effects(self, stable_id: str, *, label: str = ...) -> RouteBuilder: ...
