from __future__ import annotations

from typing import Any, Optional, Tuple

from infernux.renderstack.render_effect_asset import RenderEffectAsset, RenderEffectGroupAsset

class EditableRenderEffectGroup:
    file_path: str
    guid: str
    def __init__(self, source: RenderEffectGroupAsset, *, file_path: str = ..., guid: str = ...) -> None: ...
    @property
    def entries(self) -> tuple: ...
    def to_asset(self) -> RenderEffectGroupAsset: ...
    def serialize_document(self) -> dict[str, Any]: ...
    def deserialize_document(self, document: Any) -> bool: ...

class RenderEffect:
    _suppress_auto_save: bool
    def __init__(self, source: RenderEffectAsset, *, file_path: str = ..., guid: str = ...) -> None: ...
    @classmethod
    def load(cls, file_path: str) -> Optional[RenderEffect]: ...
    @property
    def feature_type(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def guid(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def revision(self) -> int: ...
    @property
    def artifact_revision(self) -> int: ...
    def to_asset(self) -> RenderEffectAsset: ...
    def to_dict(self) -> dict[str, Any]: ...
    def has_parameter(self, name: str) -> bool: ...
    def get_param(self, name: str, default: Any = ...) -> Any: ...
    def set_param(self, name: str, value: Any) -> None: ...
    def set_float(self, name: str, value: float) -> None: ...
    def get_float(self, name: str, default: float = ...) -> float: ...
    def set_int(self, name: str, value: int) -> None: ...
    def get_int(self, name: str, default: int = ...) -> int: ...
    def set_bool(self, name: str, value: bool) -> None: ...
    def get_bool(self, name: str, default: bool = ...) -> bool: ...
    def set_vector2(self, name: str, x: float, y: float) -> None: ...
    def get_vector2(self, name: str) -> Tuple[float, float]: ...
    def set_vector3(self, name: str, x: float, y: float, z: float) -> None: ...
    def get_vector3(self, name: str) -> Tuple[float, float, float]: ...
    def set_vector4(self, name: str, x: float, y: float, z: float, w: float) -> None: ...
    def get_vector4(self, name: str) -> Tuple[float, float, float, float]: ...
    def set_color(self, name: str, r: float, g: float, b: float, a: float = ...) -> None: ...
    def get_color(self, name: str) -> Tuple[float, float, float, float]: ...
    def clone(self) -> RenderEffect: ...
    def save(self, file_path: str = ...) -> bool: ...
    def flush(self) -> None: ...
    @classmethod
    def flush_all_pending(cls) -> None: ...
