from __future__ import annotations

from typing import List, Tuple
from Infernux.lib import Vector3, quatf

from Infernux.components.builtin.mesh_renderer import MeshRenderer


class SkinnedMeshRenderer(MeshRenderer):
    _cpp_type_name: str
    _component_category_: str

    @property
    def source_model_guid(self) -> str: ...
    @property
    def active_take_name(self) -> str: ...
    @active_take_name.setter
    def active_take_name(self, value: str) -> None: ...
    @property
    def animation_source_guid(self) -> str: ...
    @property
    def animation_take_count(self) -> int: ...
    @property
    def has_animation_takes(self) -> bool: ...
    @property
    def runtime_animation_time(self) -> float: ...
    @property
    def runtime_animation_normalized_time(self) -> float: ...

    def get_animation_take_names(self) -> List[str]: ...
    def set_source_model_guid(self, guid: str) -> None: ...
    def get_root_motion_delta(
        self, take_name: str, from_seconds: float, to_seconds: float,
        loop: bool = True, animation_source_guid: str = "",
    ) -> Tuple[Vector3, quatf]: ...
