from typing import Any, Iterable, Optional

class AssetReferenceType:
    type_id: str
    display_name: str
    extensions: frozenset[str]
    drag_types: tuple[str, ...]
    widget_prefix: str
    aliases: tuple[str, ...]
    allow_structured_reference: bool
    virtual_path_markers: tuple[str, ...]
    @property
    def patterns(self) -> tuple[str, ...]: ...
    def incompatibility(self, payload: Any) -> str: ...

class AssetReferenceCodec:
    PREFIX: str
    @classmethod
    def encode(cls, asset_type: str, value: Any) -> str: ...
    @classmethod
    def decode(cls, text: str) -> dict[str, str]: ...
    @staticmethod
    def normalize(asset_type: str, value: Any) -> dict[str, str]: ...

class AssetTypeRegistry:
    def register(self, descriptor: AssetReferenceType, *, replace: bool = False) -> None: ...
    def get(self, type_or_alias: str) -> Optional[AssetReferenceType]: ...
    def require(self, type_or_alias: str) -> AssetReferenceType: ...
    def values(self) -> tuple[AssetReferenceType, ...]: ...

asset_type_registry: AssetTypeRegistry
def resolve_asset_reference_path(asset_type: str, value: Any) -> str: ...
