from __future__ import annotations

from typing import Any

from Infernux.components import SerializableObject

DATA_ASSET_EXTENSION: str
DATA_ASSET_ARTIFACT_EXTENSION: str
DATA_ASSET_DOCUMENT_TYPE: str

class DataAsset(SerializableObject):
    __serialized_type_id__: str
    def __init__(self, **kwargs: Any) -> None: ...
    @property
    def guid(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def is_persistent(self) -> bool: ...
    def serialize_document(self) -> dict[str, Any]: ...
    @classmethod
    def from_document(cls, document: dict[str, Any]) -> DataAsset: ...
    def deserialize_document(self, document: dict[str, Any]) -> bool: ...
    @classmethod
    def load(cls, path: str) -> DataAsset: ...
    def save_to(self, path: str, *, database: Any = ...) -> str: ...
    def save(self) -> None: ...
    def instantiate(self) -> DataAsset: ...

def get_registered_data_asset_types() -> tuple[tuple[str, type[DataAsset]], ...]: ...
def encode_data_asset_artifact(document: dict[str, Any]) -> bytes: ...
def decode_data_asset_artifact(payload: bytes) -> dict[str, Any]: ...
