from __future__ import annotations

from typing import Any, Iterable, Mapping, Optional, Sequence

from Infernux.lib import InxMesh

class Mesh:
    def __init__(self, native: InxMesh) -> None: ...
    @staticmethod
    def create(name: str = "Mesh") -> Mesh: ...
    @staticmethod
    def from_data(positions: Any, indices: Any, *, normals: Any = None, uvs: Any = None, tangents: Any = None, colors: Any = None, submeshes: Optional[Iterable[Mapping[str, Any]]] = None, material_slots: Sequence[str] = (), name: str = "Mesh") -> Mesh: ...
    @staticmethod
    def load(path: str) -> Optional[Mesh]: ...
    @staticmethod
    def load_guid(guid: str) -> Optional[Mesh]: ...
    @staticmethod
    def from_native(native: InxMesh) -> Mesh: ...
    @property
    def native(self) -> InxMesh: ...
    @property
    def name(self) -> str: ...
    @property
    def guid(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def generation(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def index_count(self) -> int: ...
    @property
    def submesh_count(self) -> int: ...
    @property
    def material_slots(self) -> tuple[str, ...]: ...
    @property
    def model_nodes(self) -> tuple[dict[str, Any], ...]: ...
    @property
    def bounds(self) -> tuple[float, float, float, float, float, float]: ...
    @property
    def vertex_buffer(self) -> dict[str, Any]: ...
    @property
    def index_buffer(self) -> Any: ...
    def get_submesh(self, index: int) -> dict[str, Any]: ...
    def copy(self, name: str = "") -> Mesh: ...
    def destroy(self) -> None: ...
    def set_data(self, positions: Any, indices: Any, *, normals: Any = None, uvs: Any = None, tangents: Any = None, colors: Any = None, submeshes: Optional[Iterable[Mapping[str, Any]]] = None, material_slots: Sequence[str] = ()) -> None: ...
    def update_vertices(self, first: int, *, positions: Any = None, normals: Any = None, uvs: Any = None, tangents: Any = None, colors: Any = None) -> None: ...
    def recalculate_normals(self) -> None: ...
    def recalculate_tangents(self) -> None: ...
    def serialize_source(self) -> bytes: ...
