from Infernux.lib import PixelFormat

class RenderTexture:
    @classmethod
    def load(cls, path: str) -> RenderTexture: ...
    @classmethod
    def load_by_guid(cls, guid: str) -> RenderTexture: ...
    @property
    def guid(self) -> str: ...
    @property
    def file_path(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    def __init__(self, width: int | None = None, height: int | None = None, *,
                 scale: tuple[float, float] | None = None, format: PixelFormat = ...,
                 depth_format: PixelFormat = ..., samples: int = 1,
                 filter: str = "linear", storage: bool = False,
                 sampled_depth: bool = False) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def scale(self) -> tuple[float, float] | None: ...
    @property
    def format(self) -> PixelFormat: ...
    @property
    def depth_format(self) -> PixelFormat: ...
    @property
    def samples(self) -> int: ...
    @property
    def sampled_depth(self) -> bool: ...
    @property
    def revision(self) -> int: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def resident_bytes(self) -> int: ...
    def resize(self, width: int, height: int) -> bool: ...
