from __future__ import annotations

from os import PathLike

class SandboxPath:
    def __init__(self, path: str | PathLike[str]) -> None: ...
    @classmethod
    def create(cls, path: str | PathLike[str]) -> SandboxPath: ...
    @property
    def relative_path(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def is_file(self) -> bool: ...
    def read_bytes(self) -> bytes: ...
    def read_text(self, encoding: str = ...) -> str: ...
    def write_bytes(self, data: bytes | bytearray | memoryview) -> int: ...
    def write_text(self, text: str, encoding: str = ...) -> int: ...
    def delete(self) -> None: ...

def find_sandbox_paths(pattern: str | PathLike[str]) -> list[SandboxPath]: ...

__all__: list[str]
