from collections.abc import Callable
from typing import Optional, TypeAlias

AssetRenameTransform: TypeAlias = Callable[[str, str, str], str]

class AssetRenameContentRegistry:
    @classmethod
    def instance(cls) -> AssetRenameContentRegistry: ...
    def register(self, extensions, transform: AssetRenameTransform) -> None: ...
    def unregister(self, extension: str) -> None: ...
    def build_patch(self, source: str, destination: str) -> Optional[tuple[str, str]]: ...
    def shutdown(self) -> None: ...
