from typing import Any

class AuthoringAssetSnapshot:
    target_path: str
    source_text: str
    content_token: str
    title: str
    payload: Any
    def __init__(self, target_path: str, source_text: str, content_token: str, title: str, payload: Any = ...) -> None: ...

class AuthoringDocumentController:
    def __init__(self, view: Any) -> None: ...
    @property
    def view(self) -> Any: ...
    def save(self, *, ticket, save_as: bool = ...) -> Any: ...
    @property
    def publication_error(self) -> str: ...
    def continue_save_to_resource(self, save_ticket_id: str, resource_path: str) -> Any: ...
    def save_to_resource(self, *, ticket, resource_path: str) -> Any: ...
    def poll_pending_writes(self) -> int: ...
    def poll_save(self, ticket) -> Any: ...
    def discard(self, *, document_id: str) -> Any: ...
    def resource_moved(
        self,
        *,
        document_id: str,
        source_path: str,
        destination_path: str,
        guid: str,
    ) -> Any: ...
    def capture_document_restore_state(self, document_id: str) -> Any: ...
    def restore_document_restore_state(self, state: Any) -> None: ...
    def open_resource_immediate(self, resource_path: str) -> bool: ...
    def capture_authoring_snapshot(self) -> Any: ...
    def restore_authoring_snapshot(self, state: Any) -> None: ...
    def capture_graph_diff_checkpoint(self) -> Any: ...
    def restore_graph_diff_checkpoint(self, checkpoint: Any) -> None: ...
    def apply_diff(self, diff: Any) -> None: ...
    def on_graph_diff_applied(self, diff: Any) -> None: ...
    def timeline_authoring_model(self) -> Any: ...
    def on_timeline_authoring_applied(self) -> None: ...
