from typing import Iterable, Mapping

class CollectionSelection:
    selected_ids: tuple[str, ...]
    primary_id: str
    anchor_id: str
    cursor_id: str

class CollectionRenameSession:
    item_id: str
    original_value: str
    buffer: str
    focus_pending: bool

class CollectionInsertion:
    index: int
    dragged_ids: tuple[str, ...]

class CollectionViewport:
    first_index: int
    last_index: int
    item_ids: tuple[str, ...]

class CollectionInteractionModel:
    def __init__(self, item_ids: Iterable[object] = ...) -> None: ...
    @property
    def revision(self) -> int: ...
    @property
    def ordered_ids(self) -> tuple[str, ...]: ...
    @property
    def selection(self) -> CollectionSelection: ...
    @property
    def rename_session(self) -> CollectionRenameSession | None: ...
    @property
    def insertion(self) -> CollectionInsertion | None: ...
    def contains(self, item_id: object) -> bool: ...
    def set_items(self, item_ids: Iterable[object]) -> bool: ...
    def project_selection(self, selected_ids: Iterable[object], *, primary_id: object = ..., preserve_anchor: bool = ...) -> bool: ...
    def clear_selection(self) -> bool: ...
    def activate(self, item_id: object, *, toggle: bool = ..., extend: bool = ...) -> CollectionSelection: ...
    def move_cursor(self, offset: int, *, extend: bool = ..., wrap: bool = ...) -> CollectionSelection: ...
    def move_to_edge(self, *, last: bool = ..., extend: bool = ...) -> CollectionSelection: ...
    def viewport(self, first_index: int, visible_count: int, *, overscan: int = ...) -> CollectionViewport: ...
    def begin_rename(self, item_id: object, value: object) -> CollectionRenameSession: ...
    def update_rename(self, value: object) -> bool: ...
    def consume_rename_focus(self) -> bool: ...
    def rename_candidate(self) -> tuple[str, str] | None: ...
    def finish_rename(self) -> bool: ...
    def cancel_rename(self) -> bool: ...
    def set_insertion(self, index: int, dragged_ids: Iterable[object] = ...) -> CollectionInsertion: ...
    def clear_insertion(self) -> bool: ...

class TreeProjectionRow:
    item_id: str
    parent_id: str
    depth: int
    sibling_index: int
    expanded: bool
    has_children: bool

class TreeProjectionModel:
    def __init__(self, expanded_ids: Iterable[object] = ...) -> None: ...
    @property
    def revision(self) -> int: ...
    @property
    def expanded_ids(self) -> frozenset[str]: ...
    def is_expanded(self, item_id: object) -> bool: ...
    def set_expanded(self, item_id: object, expanded: bool) -> bool: ...
    def replace_expanded(self, item_ids: Iterable[object]) -> bool: ...
    def toggle(self, item_id: object) -> bool: ...
    def reconcile(self, valid_ids: Iterable[object]) -> bool: ...
    def reveal_ancestors(self, item_id: object, parent_by_id: Mapping[str, object]) -> bool: ...
    def project(self, root_ids: Iterable[object], children_by_id: Mapping[str, Iterable[object]]) -> tuple[TreeProjectionRow, ...]: ...
