from typing import Optional

from .commands import CommandContext, CommandResult, EditorCommandRegistry
from .contexts import FocusService
from .modals import ModalService
from .shortcuts import ShortcutRouter

COMMAND_PALETTE_MODAL_ID: str
COMMAND_PALETTE_CONTEXT_ID: str

class CommandPaletteEntry:
    command_id: str
    display_name: str
    category: str
    shortcut: str
    enabled: bool
    disabled_reason: str
    def __init__(self, command_id: str, display_name: str, category: str, shortcut: str, enabled: bool, disabled_reason: str = ...) -> None: ...

class CommandPaletteService:
    def __init__(self, commands: EditorCommandRegistry, shortcuts: ShortcutRouter, focus: FocusService, modals: ModalService) -> None: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def query(self) -> str: ...
    @property
    def selected_index(self) -> int: ...
    @property
    def request_search_focus(self) -> bool: ...
    @property
    def last_result(self) -> Optional[CommandResult]: ...
    @property
    def entries(self) -> tuple[CommandPaletteEntry, ...]: ...
    def register_commands(self) -> None: ...
    def open(self, context: CommandContext) -> bool: ...
    def close(self) -> bool: ...
    def shutdown(self) -> None: ...
    def set_query(self, value: object) -> bool: ...
    def move_selection(self, delta: int) -> bool: ...
    def select(self, index: int) -> bool: ...
    def execute_selected(self) -> CommandResult: ...
    def execute(self, command_id: str) -> CommandResult: ...

__all__: list[str]
