from typing import Any, Callable, ContextManager, Optional
from .action_journal import ActionOrigin

class ComponentDocumentEditResult:
    changed: bool
    value: Any

class ComponentCommandService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> Optional[ComponentCommandService]: ...
    @classmethod
    def require(cls) -> ComponentCommandService: ...
    def shutdown(self) -> None: ...
    def user_action(self, description: str, *, origin: Optional[ActionOrigin] = ...) -> ContextManager[None]: ...
    def can_record(self) -> bool: ...
    def suppress_replay(self) -> ContextManager[None]: ...
    def add(self, game_object: Any, component_type: str, *, python_instance: Any = ..., native_document: Optional[dict] = ..., initializer: Optional[Callable[[Any], None]] = ..., invoke_after_deserialize: bool = ..., target_component_id: int = ..., insert_after: bool = ..., insert_at_start: bool = ..., description: str = ..., origin: Optional[ActionOrigin] = ...) -> Any: ...
    def remove(self, game_object: Any, component: Any, *, description: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def set_field(self, component: Any, field_name: str, value: Any, *, description: str = ...) -> bool: ...
    def assign_mesh_asset(self, component: Any, asset_guid: str, *, origin: Optional[ActionOrigin] = ...) -> bool: ...
    def execute_property_changes(self, changes: list[tuple[Any, str, Any, Any, str]], *, description: str, before_selection: Any = ..., after_selection: Any = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def record_applied_property_changes(self, changes: list[tuple[Any, str, Any, Any, str]], *, description: str, before_context: Any = ..., after_context: Any = ..., before_selection: Any = ..., after_selection: Any = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def edit_document(self, component: Any, edit: Callable[[], Any], *, description: str, edit_key: str = ..., origin: Optional[ActionOrigin] = ...) -> ComponentDocumentEditResult: ...
    def restore_document(self, component: Any, document: dict, *, description: str = ..., edit_key: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def restore_many(self, edits: list[tuple[Any, dict, str, str]], *, description: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def remove_many(self, entries: list[tuple[Any, Any]], *, before_selection: Any, after_selection: Any, description: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def reorder(self, changes: list[tuple[int, tuple[int, ...], tuple[int, ...]]], *, description: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def commit_documents(self, component: Any, before: dict, after: dict, *, description: str = ..., edit_key: str = ..., restore_before_execute: bool = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
    def set_material_slot(self, renderer: Any, slot: int, old_guid: str, new_guid: str, *, description: str = ..., origin: Optional[ActionOrigin] = ...) -> bool: ...
