from typing import Any, Callable, Optional

class ContinuousEditSession:
    key: str
    owner_id: str
    document_id: str
    description: str
    initial_value: Any
    current_value: Any
    metadata: dict[str, Any]
    on_commit: Optional[Callable[[ContinuousEditSession], Optional[bool]]]
    on_cancel: Optional[Callable[[ContinuousEditSession], None]]
    last_update_at: float
    @property
    def changed(self) -> bool: ...

class ContinuousEditService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> ContinuousEditService: ...
    def begin(self, key: str, *, owner_id: str, document_id: str = ..., description: str, initial_value: Any, metadata: Optional[dict[str, Any]] = ..., on_commit: Optional[Callable[[ContinuousEditSession], Optional[bool]]] = ..., on_cancel: Optional[Callable[[ContinuousEditSession], None]] = ...) -> ContinuousEditSession: ...
    def get(self, key: str) -> Optional[ContinuousEditSession]: ...
    def update(self, key: str, value: Any) -> bool: ...
    def commit_if_idle(self, key: str, *, idle_seconds: float) -> bool: ...
    def commit(self, key: str) -> bool: ...
    def cancel(self, key: str) -> bool: ...
    def commit_owner(self, owner_id: str) -> int: ...
    def cancel_owner(self, owner_id: str) -> int: ...
    def commit_document(self, document_id: str) -> int: ...
    def commit_all(self) -> int: ...
    def clear(self, *, commit: bool = ...) -> None: ...
    @property
    def active_count(self) -> int: ...
