from enum import Enum
from typing import Iterable, Optional

class SelectionDomain(str, Enum):
    SCENE_OBJECT: SelectionDomain
    ASSET: SelectionDomain
    ASSET_SUBRESOURCE: SelectionDomain
    COMPONENT: SelectionDomain
    GRAPH_ELEMENT: SelectionDomain
    TIMELINE_ELEMENT: SelectionDomain
    UI_ELEMENT: SelectionDomain
    DIAGNOSTIC_ENTRY: SelectionDomain
    SETTINGS_ELEMENT: SelectionDomain

class SelectionTarget:
    domain: SelectionDomain
    target_id: str
    document_id: str
    sub_kind: str
    def __init__(self, domain: SelectionDomain, target_id: str, document_id: str = "", sub_kind: str = "") -> None: ...
    @classmethod
    def scene_object(cls, object_id: int) -> SelectionTarget: ...
    @classmethod
    def asset(cls, guid: str) -> SelectionTarget: ...
    @classmethod
    def asset_subresource(cls, asset_guid: str, subresource_id: str, *, sub_kind: str) -> SelectionTarget: ...
    @classmethod
    def component(cls, object_id: int, component_id: int, *, document_id: str = "", sub_kind: str = "") -> SelectionTarget: ...
    @classmethod
    def graph_element(cls, document_id: str, element_id: str, *, sub_kind: str) -> SelectionTarget: ...
    @classmethod
    def timeline_element(cls, document_id: str, element_id: str, *, sub_kind: str) -> SelectionTarget: ...
    @classmethod
    def ui_element(cls, document_id: str, element_id: str, *, sub_kind: str = "") -> SelectionTarget: ...
    @classmethod
    def diagnostic_entry(cls, owner_id: str, entry_id: str, *, sub_kind: str = "log") -> SelectionTarget: ...
    @classmethod
    def settings_element(cls, document_id: str, element_id: str, *, sub_kind: str) -> SelectionTarget: ...
    def scene_object_id(self) -> int: ...
    def component_ids(self) -> tuple[int, int]: ...

class SelectionSnapshot:
    owner_id: str
    targets: tuple[SelectionTarget, ...]
    primary_index: int
    anchor_index: int
    def __init__(self, owner_id: str = "", targets: tuple[SelectionTarget, ...] = (), primary_index: int = -1, anchor_index: int = -1) -> None: ...
    @classmethod
    def create(cls, targets: Iterable[SelectionTarget], *, owner_id: str, primary: Optional[SelectionTarget] = None, anchor: Optional[SelectionTarget] = None) -> SelectionSnapshot: ...
    @property
    def primary(self) -> Optional[SelectionTarget]: ...
    @property
    def anchor(self) -> Optional[SelectionTarget]: ...
    @property
    def domain(self) -> Optional[SelectionDomain]: ...
    @property
    def is_empty(self) -> bool: ...
