from enum import Enum
from typing import Optional, Protocol
from .documents import DocumentKind, DocumentLocator, DocumentRegistry, EditorDocument

class DocumentOpenStatus(str, Enum):
    READY: DocumentOpenStatus
    PENDING: DocumentOpenStatus
    FAILED: DocumentOpenStatus

class DocumentOpenResult:
    status: DocumentOpenStatus
    document: Optional[EditorDocument]
    message: str
    def __init__(self, status: DocumentOpenStatus, document: Optional[EditorDocument] = ..., message: str = ...) -> None: ...

class DocumentOpenAdapter(Protocol):
    def __call__(self, locator: DocumentLocator) -> object: ...

class DocumentOpenService:
    def __init__(self, registry: Optional[DocumentRegistry] = ...) -> None: ...
    @property
    def registry(self) -> DocumentRegistry: ...
    def register(self, kind: DocumentKind, adapter: DocumentOpenAdapter, *, replace: bool = ...) -> None: ...
    def unregister(self, kind: DocumentKind) -> bool: ...
    def resolve_or_open(self, locator: Optional[DocumentLocator]) -> DocumentOpenResult: ...
    def open_resource(self, kind: DocumentKind, resource_path: str, *, guid: str = ..., title: str = ...) -> DocumentOpenResult: ...
    def clear(self) -> None: ...
