from enum import Enum, IntFlag
from typing import Any, Optional, Protocol

def document_content_token(value: Any) -> str: ...

class DocumentKind(str, Enum):
    SCENE: DocumentKind
    PREFAB: DocumentKind
    MATERIAL: DocumentKind
    DATA_ASSET: DocumentKind
    PHYSIC_MATERIAL: DocumentKind
    RENDER_TEXTURE: DocumentKind
    RENDER_EFFECT: DocumentKind
    ANIMATION_CLIP: DocumentKind
    ANIMATION_FSM: DocumentKind
    TIMELINE: DocumentKind
    PARTICLE_GRAPH: DocumentKind
    UI_DOCUMENT: DocumentKind
    IMPORT_SETTINGS: DocumentKind
    PROJECT_SETTINGS: DocumentKind
    GENERIC: DocumentKind

class DocumentIdentityKind(str, Enum):
    ASSET_GUID: DocumentIdentityKind
    RESOURCE_PATH: DocumentIdentityKind
    SESSION: DocumentIdentityKind

class DocumentKey:
    kind: DocumentKind
    identity_kind: DocumentIdentityKind
    identity: str
    def __init__(self, kind: DocumentKind, identity_kind: DocumentIdentityKind, identity: str) -> None: ...
    @classmethod
    def asset(cls, kind: DocumentKind, guid: str) -> DocumentKey: ...
    @classmethod
    def resource(cls, kind: DocumentKind, path: str) -> DocumentKey: ...
    @classmethod
    def session(cls, kind: DocumentKind, session_id: str = "") -> DocumentKey: ...

class DocumentLocator:
    stable_id: str
    key_hint: DocumentKey
    resource_path: str
    title: str
    def __init__(self, stable_id: str, key_hint: DocumentKey, resource_path: str = "", title: str = "") -> None: ...
    @property
    def key(self) -> DocumentKey: ...

class DocumentState(str, Enum):
    READY: DocumentState
    SAVING: DocumentState
    CONFLICT: DocumentState
    CLOSED: DocumentState

class DocumentCapability(IntFlag):
    NONE: DocumentCapability
    SAVE: DocumentCapability
    SAVE_AS: DocumentCapability
    DISCARD: DocumentCapability

class DocumentActionStatus(str, Enum):
    APPLIED: DocumentActionStatus
    PENDING: DocumentActionStatus
    NO_OP: DocumentActionStatus
    REJECTED: DocumentActionStatus
    FAILED: DocumentActionStatus

class SaveTicketStatus(str, Enum):
    PENDING: SaveTicketStatus
    SUCCEEDED: SaveTicketStatus
    FAILED: SaveTicketStatus
    CANCELLED: SaveTicketStatus

class DocumentActionResult:
    status: DocumentActionStatus
    message: str
    durable_file_state: Any
    def __init__(self, status: DocumentActionStatus, message: str = "", durable_file_state: Any = ...) -> None: ...
    @property
    def accepted(self) -> bool: ...

class SaveTicket:
    ticket_id: str
    document_id: str
    captured_revision: int
    captured_external_revision: int
    was_conflicted: bool
    expected_file_state: Any
    resource_path: str
    content_token: str
    save_as: bool
    operation_id: str
    commit_token: str
    publication_bookkeeping_revision: Optional[int]
    status: SaveTicketStatus
    message: str
    @property
    def is_pending(self) -> bool: ...

class DocumentController(Protocol):
    def save(self, *, ticket: SaveTicket, save_as: bool = False) -> Any: ...
    def discard(self, *, document_id: str) -> Any: ...
    def reload_from_resource(self, *, document_id: str, resource_path: str) -> Any: ...
    def resource_moved(self, *, document_id: str, source_path: str, destination_path: str, guid: str) -> Any: ...

class ExplicitResourceSaveController(Protocol):
    def save_to_resource(self, *, ticket: SaveTicket, resource_path: str) -> Any: ...

class EditorDocument:
    document_id: str
    stable_id: str
    key: DocumentKey
    kind: DocumentKind
    title: str
    resource_path: str
    revision: int
    saved_revision: int
    external_revision: int
    edit_revision: int
    requested_write_revision: int
    persisted_revision: int
    imported_disk_revision: int
    preview_dependency_revision: int
    durable_file_state: Any
    external_file_state: Any
    state: DocumentState
    capabilities: DocumentCapability
    view_ids: set[str]
    dirty_view_ids: set[str]
    controller: Optional[DocumentController]
    @property
    def is_dirty(self) -> bool: ...
    def is_dirty_for_view(self, view_id: str) -> bool: ...
    def dirty_owner_view_ids(self) -> frozenset[str]: ...

class DocumentRegistry:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> DocumentRegistry: ...
    @property
    def revision(self) -> int: ...
    @property
    def documents(self) -> tuple[EditorDocument, ...]: ...
    def has_pending_session_document(self, view_id: str) -> bool: ...
    def pending_session_view_ids(self) -> tuple[str, ...]: ...
    def prune_pending_session_views(self, restorable_view_ids) -> tuple[str, ...]: ...
    def is_session_restore_suppressed(self, view_id: str) -> bool: ...
    def capture_session_state(self) -> dict[str, Any]: ...
    def queue_session_restore(self, data: Optional[dict[str, Any]]) -> int: ...
    def claim_session_document(self, view_id: str, *, controller: DocumentController) -> Optional[tuple[EditorDocument, Any]]: ...
    def create(self, kind: DocumentKind, title: str, *, document_id: str = "", stable_id: str = "", key: Optional[DocumentKey] = None, resource_path: str = "", revision: int = 0, saved_revision: Optional[int] = None, external_revision: int = 0, state: DocumentState = DocumentState.READY, dirty_view_ids: tuple[str, ...] | list[str] | set[str] = (), capabilities: DocumentCapability = DocumentCapability.NONE, controller: Optional[DocumentController] = None) -> EditorDocument: ...
    def get(self, document_id: str) -> Optional[EditorDocument]: ...
    def require(self, document_id: str) -> EditorDocument: ...
    def get_by_key(self, key: DocumentKey) -> Optional[EditorDocument]: ...
    def locate(self, document_id: str) -> Optional[DocumentLocator]: ...
    def canonical_locator(self, locator: DocumentLocator) -> DocumentLocator: ...
    def locate_resource(self, kind: DocumentKind, resource_path: str, *, guid: str = ..., title: str = ...) -> DocumentLocator: ...
    def resolve_locator(self, locator: Optional[DocumentLocator]) -> Optional[EditorDocument]: ...
    def open_or_create(self, key: DocumentKey, title: str, *, stable_id: str = "", resource_path: str = "", revision: int = 0, saved_revision: Optional[int] = None, capabilities: DocumentCapability = DocumentCapability.NONE, controller: Optional[DocumentController] = None) -> tuple[EditorDocument, bool]: ...
    def rekey(self, document_id: str, key: DocumentKey, *, resource_path: Optional[str] = None) -> bool: ...
    def document_for_view(self, view_id: str) -> Optional[EditorDocument]: ...
    def attach_view(self, document_id: str, view_id: str) -> bool: ...
    def replace_view_document(self, document_id: str, view_id: str) -> bool: ...
    def detach_view(self, view_id: str) -> Optional[str]: ...
    def close_view(self, view_id: str, *, preserve_dormant: bool = ...) -> Optional[str]: ...
    def unregister(self, document_id: str, *, preserve_dormant: bool = True) -> bool: ...
    def restore_dormant(self, locator: DocumentLocator, *, controller: Optional[DocumentController] = None) -> Optional[EditorDocument]: ...
    def dormant_restore_state(self, locator: DocumentLocator) -> Any: ...
    def update_metadata(self, document_id: str, *, title: Optional[str] = None, resource_path: Optional[str] = None, capabilities: Optional[DocumentCapability] = None, controller: Optional[DocumentController] = None) -> bool: ...
    def remap_resource_path(self, source_path: str, destination_path: str, *, guid: str = ..., title: str = ...) -> tuple[str, ...]: ...
    def preflight_resource_remaps(self, remaps) -> None: ...
    def mark_changed(self, document_id: str, *, view_id: str = "") -> int: ...
    def reserve_content_revision(self, document_id: str) -> int: ...
    def reserve_changed_revision(self, document_id: str, *, view_id: str = "") -> int: ...
    def mark_saved(self, document_id: str, revision: Optional[int] = None) -> int: ...
    def establish_loaded_baseline(self, document_id: str, *, durable_file_state: Any = ...) -> int: ...
    def restore_saved_revision(self, document_id: str) -> int: ...
    def abandon_session_changes(self, document_id: str) -> int: ...
    def retire_deleted_resource_document(self, document_id: str) -> tuple[str, ...]: ...
    def restore_content_revision(self, document_id: str, revision: int) -> int: ...
    def mark_conflict(self, document_id: str) -> None: ...
    def documents_for_resource(self, resource_path: str) -> tuple[EditorDocument, ...]: ...
    def documents_under_resource(self, resource_path: str) -> tuple[EditorDocument, ...]: ...
    def durable_resource_content_changed(self, resource_path: str, *, deleted: bool = False) -> Optional[bool]: ...
    def publish_external_resource_change(self, resource_path: str, *, deleted: bool = False) -> tuple[str, ...]: ...
    def preflight_external_resource_change(self, resource_path: str, *, deleted: bool = False) -> bool: ...
    def has_pending_external_change_preflight(self, resource_path: str) -> bool: ...
    def fail_external_resource_change(self, resource_path: str, *, message: str = "") -> tuple[str, ...]: ...
    def request_reload_external(self, document_id: str) -> DocumentActionResult: ...
    def complete_external_reload(self, document_id: str, *, success: bool, message: str = "", durable_file_state: Any = ...) -> DocumentActionResult: ...
    def take_external_reload_result(self, document_id: str) -> Optional[DocumentActionResult]: ...
    def resolve_conflict_keep_local(self, document_id: str) -> DocumentActionResult: ...
    def restore_revision_state(self, document_id: str, *, revision: int, saved_revision: int, state: DocumentState = DocumentState.READY) -> None: ...
    def dirty_documents(self) -> tuple[EditorDocument, ...]: ...
    def request_save(self, document_id: str, *, save_as: bool = False) -> DocumentActionResult: ...
    def request_save_to_resource(self, document_id: str, resource_path: str) -> DocumentActionResult: ...
    def defer_save(self, document_id: str, *, save_as: bool = False) -> DocumentActionResult: ...
    def process_deferred_saves(self) -> tuple[DocumentActionResult, ...]: ...
    def process_pending_saves(self) -> int: ...
    def begin_save(self, document_id: str, *, save_as: bool = False) -> SaveTicket: ...
    def active_save_ticket(self, document_id: str) -> Optional[SaveTicket]: ...
    def get_save_ticket(self, ticket_id: str) -> Optional[SaveTicket]: ...
    def capture_save_revision(self, ticket_id: str, *, content_token: str = "") -> int: ...
    def capture_save_target(self, ticket_id: str, resource_path: str) -> Any: ...
    def mark_save_publication_bookkeeping(self, ticket_id: str) -> int: ...
    def complete_save(self, ticket_id: str, *, success: bool, cancelled: bool = False, key: Optional[DocumentKey] = None, resource_path: Optional[str] = None, title: Optional[str] = None, content_token: Optional[str] = None, committed_file_state: Any = None, conflict: bool = False, message: str = "") -> SaveTicket: ...
    def request_discard(self, document_id: str) -> DocumentActionResult: ...
    def is_save_pending(self, document_id: str) -> bool: ...
    def clear(self) -> None: ...
