from typing import Optional

from .documents import DocumentActionResult, DocumentRegistry

class ExternalDocumentConflict:
    conflict_id: str
    document_id: str
    external_revision: int
    resource_path: str
    title: str

class ExternalDocumentConflictService:
    def __init__(self, registry: DocumentRegistry) -> None: ...
    @property
    def active(self) -> Optional[ExternalDocumentConflict]: ...
    @property
    def active_document(self): ...
    @property
    def is_active(self) -> bool: ...
    @property
    def waiting_for_save_copy(self) -> bool: ...
    @property
    def waiting_for_reload(self) -> bool: ...
    @property
    def error(self) -> str: ...
    def poll(self) -> None: ...
    def reload(self, conflict_id: str) -> DocumentActionResult: ...
    def keep_local(self, conflict_id: str) -> DocumentActionResult: ...
    def save_copy(self, conflict_id: str) -> DocumentActionResult: ...
    def clear(self) -> None: ...

__all__: list[str]
