from enum import Enum
from typing import Callable, Iterable, Optional, Protocol, Sequence
from .descriptors import SelectionSnapshot, SelectionTarget
from .selection import SelectionService

class GraphElementKind(str, Enum):
    GRAPH: GraphElementKind
    NODE: GraphElementKind
    LINK: GraphElementKind
    PARAMETER: GraphElementKind
    EVENT_TYPE: GraphElementKind
    EVENT_FLOW: GraphElementKind
    EMITTER: GraphElementKind
    ATTRIBUTE: GraphElementKind
    DATA_INTERFACE: GraphElementKind

class GraphElementRef:
    kind: GraphElementKind
    stable_id: str
    def __init__(self, kind: GraphElementKind, stable_id: str) -> None: ...
    def selection_target(self, document_id: str) -> SelectionTarget: ...
    @classmethod
    def from_selection_target(cls, target: SelectionTarget, *, document_id: str) -> Optional[GraphElementRef]: ...

class GraphMutationKind(str, Enum):
    INSERT: GraphMutationKind
    REMOVE: GraphMutationKind
    UPDATE: GraphMutationKind
    MOVE: GraphMutationKind

class GraphMutation:
    kind: GraphMutationKind
    element: GraphElementRef
    before: object
    after: object
    before_index: int
    after_index: int
    def __init__(self, kind: GraphMutationKind, element: GraphElementRef, before: object = ..., after: object = ..., before_index: int = ..., after_index: int = ...) -> None: ...
    def inverted(self) -> GraphMutation: ...

class GraphActionDiff:
    document_id: str
    mutations: tuple[GraphMutation, ...]
    before_revision: int
    after_revision: int
    def __init__(self, document_id: str, mutations: tuple[GraphMutation, ...], before_revision: int = ..., after_revision: int = ...) -> None: ...
    def inverted(self) -> GraphActionDiff: ...

class GraphDomainAdapter(Protocol):
    def contains(self, element: GraphElementRef) -> bool: ...
    def apply_diff(self, diff: GraphActionDiff) -> None: ...

class GraphSelectionController:
    owner_id: str
    def __init__(self, *, owner_id: str, document_id: Callable[[], str], contains: Callable[[GraphElementRef], bool], view = ..., element_from_view: Optional[Callable[[GraphElementKind, str], GraphElementRef]] = ..., element_to_view: Optional[Callable[[GraphElementRef], str]] = ..., on_changed: Optional[Callable[[tuple[GraphElementRef, ...]], None]] = ...) -> None: ...
    @property
    def elements(self) -> tuple[GraphElementRef, ...]: ...
    @property
    def primary(self) -> Optional[GraphElementRef]: ...
    def primary_id(self, kind: GraphElementKind) -> str: ...
    def selected_ids(self, kind: GraphElementKind) -> tuple[str, ...]: ...
    def bind(self, service: Optional[SelectionService] = ...) -> None: ...
    def unbind(self) -> None: ...
    def set_view(self, view) -> None: ...
    def refresh(self) -> None: ...
    def select(self, elements: Iterable[GraphElementRef], *, reason: str = ..., record_history: bool = ...) -> bool: ...
    def select_one(self, kind: GraphElementKind, stable_id: str, *, reason: str = ..., record_history: bool = ...) -> bool: ...
    def clear(self, *, reason: str = ..., record_history: bool = ...) -> bool: ...
    def accept_view_selection(self, node_ids: Sequence[str], link_id: str, *, record_history: bool) -> bool: ...
    def project(self, snapshot: SelectionSnapshot) -> None: ...
