from typing import Any

class GraphCommandService:
    def __init__(self, panels: Any) -> None: ...
    @classmethod
    def instance(cls) -> GraphCommandService | None: ...
    def register_commands(self, registry: Any) -> None: ...
    def shutdown(self) -> None: ...
