from collections.abc import Callable
from enum import Enum
from typing import Any

Vec3 = tuple[float, float, float]

class EditorHandleKind(str, Enum):
    POSITION: EditorHandleKind
    DIRECTION: EditorHandleKind
    RADIUS: EditorHandleKind
    LIMIT: EditorHandleKind

class EditorHandleProvider:
    provider_id: str
    draw: Callable[[EditorHandleContext], object]
    enabled: Callable[[], bool] | None
    on_retire: Callable[[], object] | None
    def __init__(self, provider_id: str, draw: Callable[[EditorHandleContext], object], enabled: Callable[[], bool] | None = ..., on_retire: Callable[[], object] | None = ...) -> None: ...

class EditorHandleSnapshot:
    handle_id: str
    provider_id: str
    kind: EditorHandleKind
    value: Any
    position: Vec3
    direction: Vec3
    size: float

class HandleRegistration:
    provider_id: str
    @property
    def closed(self) -> bool: ...
    def close(self) -> bool: ...
    def __enter__(self) -> HandleRegistration: ...
    def __exit__(self, type: object, value: object, traceback: object) -> None: ...

class EditorHandleContext:
    engine: object
    selection: object
    provider_id: str
    def position(self, handle_id: str, value: Vec3, on_changed: Callable[[Vec3], object], *, size: float = ..., color: Vec3 = ..., on_begin: Callable[[Vec3], object] | None = ..., on_commit: Callable[[Vec3], object] | None = ..., on_cancel: Callable[[Vec3], object] | None = ...) -> None: ...
    def direction(self, handle_id: str, origin: Vec3, value: Vec3, on_changed: Callable[[Vec3], object], *, length: float = ..., size: float = ..., color: Vec3 = ..., on_begin: Callable[[Vec3], object] | None = ..., on_commit: Callable[[Vec3], object] | None = ..., on_cancel: Callable[[Vec3], object] | None = ...) -> None: ...
    def radius(self, handle_id: str, center: Vec3, value: float, on_changed: Callable[[float], object], *, size: float = ..., color: Vec3 = ..., on_begin: Callable[[float], object] | None = ..., on_commit: Callable[[float], object] | None = ..., on_cancel: Callable[[float], object] | None = ...) -> None: ...
    def limit(self, handle_id: str, origin: Vec3, axis: Vec3, value: tuple[float, float], on_changed: Callable[[tuple[float, float]], object], *, size: float = ..., color: Vec3 = ..., on_begin: Callable[[tuple[float, float]], object] | None = ..., on_commit: Callable[[tuple[float, float]], object] | None = ..., on_cancel: Callable[[tuple[float, float]], object] | None = ...) -> None: ...

class EditorHandleRegistry:
    @classmethod
    def instance(cls) -> EditorHandleRegistry: ...
    @property
    def revision(self) -> int: ...
    @property
    def providers(self) -> tuple[EditorHandleProvider, ...]: ...
    @property
    def frame_handles(self) -> tuple[EditorHandleSnapshot, ...]: ...
    @property
    def active_capture_id(self) -> str: ...
    @property
    def hovered_handle_id(self) -> str: ...
    def register(self, provider: EditorHandleProvider, *, replace: bool = ...) -> HandleRegistration: ...
    def unregister(self, provider_id: str) -> bool: ...
    def unregister_owner(self, owner: str) -> int: ...
    def clear(self) -> None: ...
    def collect(self, engine: object) -> None: ...
    def retire_frame(self) -> None: ...
    def hit_test(self, ray_origin: Vec3, ray_direction: Vec3) -> str: ...
    def set_hovered(self, handle_id: str) -> None: ...
    def begin_capture(self, handle_id: str, ray_origin: Vec3, ray_direction: Vec3, *, interaction_owner: str = ...) -> bool: ...
    def update_capture(self, ray_origin: Vec3, ray_direction: Vec3) -> bool: ...
    def finish_capture(self, *, commit: bool = ...) -> bool: ...
    def cancel_capture(self) -> bool: ...
    def process_pointer(self, engine: object, mouse_x: float, mouse_y: float, width: float, height: float, *, left_down: bool, left_clicked: bool, hovered: bool) -> bool: ...

def register_handle_provider(provider_id: str, draw: Callable[[EditorHandleContext], object], *, enabled: Callable[[], bool] | None = ..., on_retire: Callable[[], object] | None = ..., replace: bool = ...) -> HandleRegistration: ...

__all__: list[str]
