from collections.abc import Callable
from typing import Any, Iterable, Optional

class ModalRegistration:
    modal_id: str
    is_active: Callable[[], bool]
    render: Callable[[Any], object]
    cancel: Callable[[], None]
    allowed_parent_ids: frozenset[str]

class ActiveModal:
    modal_id: str
    owner_id: str
    parent_id: str
    presented: Optional[bool]

class ModalService:
    def __init__(self) -> None: ...
    @property
    def active_modal_id(self) -> str: ...
    @property
    def active_owner_id(self) -> str: ...
    @property
    def active_stack(self) -> tuple[ActiveModal, ...]: ...
    def register(self, modal_id: str, *, is_active: Callable[[], bool], render: Callable[[Any], object], cancel: Callable[[], None], allowed_parent_ids: Iterable[str] = ...) -> None: ...
    def unregister(self, modal_id: str, *, cancel: bool = True) -> None: ...
    def activate(self, modal_id: str, *, owner_id: str = ..., parent_id: str = ...) -> bool: ...
    def deactivate(self, modal_id: str) -> bool: ...
    def cancel(self, modal_id: str) -> bool: ...
    def cancel_active(self) -> bool: ...
    def cancel_owner(self, owner_id: str) -> bool: ...
    def is_presented(self, modal_id: str) -> bool: ...
    def render(self, ctx: Any) -> None: ...
    def clear(self, *, cancel: bool = True) -> None: ...
