from dataclasses import dataclass
from typing import Callable, Optional
from .descriptors import SelectionDomain, SelectionTarget
from .selection import SelectionService

@dataclass(frozen=True)
class NavigationRequest:
    record_history: bool = ...
    activate_panel: bool = ...

NavigationAdapter = Callable[[SelectionTarget, NavigationRequest], bool]

class DirectoryNavigationSnapshot:
    current_path: str
    back_paths: tuple[str, ...]
    forward_paths: tuple[str, ...]

class DirectoryNavigationHistory:
    def __init__(self, max_entries: int = ...) -> None: ...
    @property
    def snapshot(self) -> DirectoryNavigationSnapshot: ...
    @property
    def can_go_back(self) -> bool: ...
    @property
    def can_go_forward(self) -> bool: ...
    def sync(self, current_path: str) -> None: ...
    def navigate(self, target_path: str, apply: Callable[[str], object]) -> bool: ...
    def back(self, apply: Callable[[str], object]) -> bool: ...
    def forward(self, apply: Callable[[str], object]) -> bool: ...
    def clear(self) -> None: ...

class NavigationService:
    def __init__(self, selection: Optional[SelectionService] = ...) -> None: ...
    def register(self, domain: SelectionDomain, adapter: NavigationAdapter,
                 *, replace: bool = ...) -> None: ...
    def unregister(self, domain: SelectionDomain) -> bool: ...
    def locate(self, target: SelectionTarget, *, owner_id: str,
               reason: str = ..., record_history: bool = ...,
               activate_panel: bool = ...) -> bool: ...
    def reveal(self, target: SelectionTarget, *, record_history: bool = ...,
               activate_panel: bool = ...) -> bool: ...
    def clear(self) -> None: ...
