from collections.abc import Callable, Iterable, Mapping
from typing import Optional
from .commands import CommandContext
from .descriptors import SelectionDomain
from .shortcuts import KeyChord, ShortcutBinding, ShortcutPhase

class ExternalDropKind(str):
    FILES: ExternalDropKind

class PanelCommandSpec:
    command_id: str
    def __init__(self, command_id: str) -> None: ...

class PanelShortcutSpec:
    command_id: str
    chord: KeyChord
    child_context_id: str
    phase: ShortcutPhase
    priority: int
    allow_when_text_input: bool
    allow_when_modal: bool
    allow_when_captured: bool
    def __init__(self, command_id: str, chord: KeyChord, child_context_id: str = "", phase: ShortcutPhase = ShortcutPhase.PRESS, priority: int = 0, allow_when_text_input: bool = False, allow_when_modal: bool = False, allow_when_captured: bool = False) -> None: ...

class BoundPanelCommand:
    execute: Callable[[CommandContext], object]
    can_execute: Callable[[CommandContext], bool]
    def __init__(self, execute: Callable[[CommandContext], object], can_execute: Callable[[CommandContext], bool]) -> None: ...

class PanelCommandAdapter:
    def __init__(self, handlers: Mapping[str, BoundPanelCommand]) -> None: ...
    @property
    def command_ids(self) -> frozenset[str]: ...
    def handler(self, command_id: str) -> Optional[BoundPanelCommand]: ...

class PanelInteractionDescriptor:
    commands: tuple[PanelCommandSpec, ...]
    shortcuts: tuple[PanelShortcutSpec, ...]
    owned_selection_domains: frozenset[SelectionDomain]
    external_drop_kinds: frozenset[ExternalDropKind]
    records_focus_history: bool
    document_backed: bool
    view_command_target_id: str
    adapter_factory: Optional[Callable[[object], PanelCommandAdapter]]
    def __init__(self, commands: tuple[PanelCommandSpec, ...] = (), shortcuts: tuple[PanelShortcutSpec, ...] = (), owned_selection_domains: frozenset[SelectionDomain] = frozenset(), external_drop_kinds: frozenset[ExternalDropKind] = frozenset(), records_focus_history: bool = True, document_backed: bool = False, view_command_target_id: str = "", adapter_factory: Optional[Callable[[object], PanelCommandAdapter]] = None) -> None: ...
    @property
    def command_ids(self) -> frozenset[str]: ...

class PanelInteractionRegistry:
    def __init__(self) -> None: ...
    @property
    def revision(self) -> int: ...
    def register_type(self, type_id: str, descriptor: PanelInteractionDescriptor, *, replace: bool = False) -> None: ...
    def unregister_type(self, type_id: str) -> bool: ...
    def descriptor(self, type_id: str) -> Optional[PanelInteractionDescriptor]: ...
    def descriptor_for_view(self, view_id: str) -> Optional[PanelInteractionDescriptor]: ...
    def type_id_for_view(self, view_id: str) -> str: ...
    def instance_for_view(self, view_id: str) -> Optional[object]: ...
    def accepts_external_drop(self, view_id: str, kind: ExternalDropKind) -> bool: ...
    def records_focus_history(self, *, type_id: str = "", view_id: str = "") -> bool: ...
    def is_document_backed(self, *, type_id: str = "", view_id: str = "") -> bool: ...
    def view_command_target(self, *, type_id: str = "", view_id: str = "") -> str: ...
    def allows_selection(self, owner_id: str, domain: SelectionDomain) -> bool: ...
    def register_selection_authority(self, owner_id: str, domains: Iterable[SelectionDomain], *, replace: bool = False) -> None: ...
    def descriptors(self) -> tuple[tuple[str, PanelInteractionDescriptor], ...]: ...
    def require_types(self, type_ids: Iterable[str]) -> None: ...
    def bind_view(self, view_id: str, type_id: str, instance: object) -> None: ...
    def unbind_view(self, view_id: str) -> bool: ...
    def owns_active(self, context: CommandContext, command_id: str) -> bool: ...
    def can_execute_active(self, context: CommandContext, command_id: str) -> bool: ...
    def execute_active(self, context: CommandContext, command_id: str) -> bool: ...
    def owns_view(self, view_id: str, command_id: str) -> bool: ...
    def can_execute_view(self, view_id: str, context: CommandContext, command_id: str) -> bool: ...
    def execute_view(self, view_id: str, context: CommandContext, command_id: str) -> bool: ...
    def iter_shortcut_bindings(self) -> Iterable[ShortcutBinding]: ...
    def clear(self) -> None: ...
