from collections.abc import Callable, Iterable
from typing import Any, Optional
from .commands import CommandSource
from .shortcut_profiles import ShortcutProfileModel
from .shortcuts import KeyChord, ShortcutBinding, ShortcutRouter

SUPPORTED_LOCALES: frozenset[str]
SUPPORTED_IDES: frozenset[str]

class PreferencesCommandService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> Optional[PreferencesCommandService]: ...
    def shutdown(self) -> None: ...
    @property
    def shortcut_profiles(self) -> ShortcutProfileModel | None: ...
    def bind_shortcuts(
        self,
        default_bindings: Iterable[ShortcutBinding],
        router: ShortcutRouter,
        *,
        load: Callable[[], object] | None = ...,
        save: Callable[[dict[str, Any]], None] | None = ...,
    ) -> ShortcutProfileModel: ...
    def register_commands(self, registry: Any) -> None: ...
    def set_locale(self, locale: object) -> bool: ...
    def set_ide(self, ide: object) -> bool: ...
    def set_blender_executable(self, executable: object) -> bool: ...
    def create_shortcut_profile(
        self,
        name: object,
        *,
        profile_id: object | None = ...,
    ) -> bool: ...
    def rename_shortcut_profile(self, profile_id: object, name: object) -> bool: ...
    def delete_shortcut_profile(self, profile_id: object) -> bool: ...
    def activate_shortcut_profile(self, profile_id: object) -> bool: ...
    def assign_shortcut(self, binding_id: object, chord: KeyChord | str | None | object) -> bool: ...
    def reset_shortcut_binding(self, binding_id: object) -> bool: ...
    def reset_shortcut_profile(self) -> bool: ...

def submit_preferences_command(
    command_id: str,
    *,
    source: CommandSource | str | None = ...,
    value: object,
) -> bool: ...
