from typing import Any, Callable, Optional

from .action_journal import ActionOrigin
from .document_open import DocumentOpenService
from .navigation import NavigationService
from .project_assets import ProjectAssetCommandService
from .selection import SelectionService

class PrefabCommandService:
    def __init__(self, selection: SelectionService, navigation: NavigationService, document_open: DocumentOpenService, project_assets: ProjectAssetCommandService, context_provider: Optional[Callable[[], object]] = ...) -> None: ...
    @classmethod
    def instance(cls) -> Optional[PrefabCommandService]: ...
    def can_execute(self, action: str, *, object_id: int = ..., path: str = ...) -> bool: ...
    def create_from_object(self, object_id: int, current_path: str = ..., *, origin: ActionOrigin = ...) -> str: ...
    def locate(self, *, object_id: int = ..., path: str = ..., record_history: bool = ...) -> bool: ...
    def open(self, *, object_id: int = ..., path: str = ..., origin: ActionOrigin = ...) -> bool: ...
    def exit(self, *, origin: ActionOrigin = ...) -> bool: ...
    def apply(self, object_id: int, *, origin: ActionOrigin = ...) -> bool: ...
    def revert(self, object_id: int, *, origin: ActionOrigin = ...) -> bool: ...
    def revert_property(self, component: Any, field_name: str, *, origin: ActionOrigin = ...) -> bool: ...
    def revert_asset_property(self, path: str, object_id: int, component_id: int, property_path: tuple[str, ...], *, expected_document: Optional[dict] = ..., origin: ActionOrigin = ...) -> bool: ...
    def revert_mode_property(self, object_id: int, component_id: int, property_path: tuple[str, ...], *, expected_document: Optional[dict] = ..., origin: ActionOrigin = ...) -> bool: ...
    def unpack(self, object_id: int, *, origin: ActionOrigin = ...) -> bool: ...
    def shutdown(self) -> None: ...
    def load_contents(self, path: str) -> Any: ...
    def save_contents(self, root: Any, path: str) -> str: ...
    def unload_contents(self, root: Any) -> None: ...
