from typing import Any, Callable, Iterable, Optional

from .action_journal import ActionOrigin
from .selection import SelectionService

class ProjectAssetCommandService:
    def save_mesh_copy(self, mesh: Any, target_path: str, *, origin: ActionOrigin = ...) -> str: ...
    def extract_model_material(self, mesh: Any, slot: int, target_path: str, *, origin: ActionOrigin = ...) -> str: ...
    def save_material_copy(self, material: Any, target_path: str, *, origin: ActionOrigin = ...) -> str: ...
    def __init__(self, selection: SelectionService) -> None: ...
    @classmethod
    def instance(cls) -> Optional[ProjectAssetCommandService]: ...
    @property
    def configured(self) -> bool: ...
    @property
    def project_root(self) -> str: ...
    @property
    def asset_database(self) -> Any: ...
    def configure(self, project_root: str, asset_database: Any = ...) -> None: ...
    def add_change_listener(self, callback: Callable[[], None]) -> None: ...
    def remove_change_listener(self, callback: Callable[[], None]) -> None: ...
    def create(self, current_path: str, creator: Callable[[], Any], *, description: str = ..., origin: ActionOrigin = ..., replace_path: str = ...) -> Any: ...
    def create_with_path(self, current_path: str, creator: Callable[[], Any], *, description: str = ..., origin: ActionOrigin = ...) -> str: ...
    def create_prefab(self, current_path: str, creator: Callable[[], Any], capture_linkage: Callable[[], Any], restore_linkage: Callable[[Any], None], *, origin: ActionOrigin = ...) -> Any: ...
    def rename(self, source_path: str, new_name: str, *, origin: ActionOrigin = ...) -> str: ...
    def can_rename(self, source_path: str, new_name: str) -> bool: ...
    def preflight_delete(self, paths: Iterable[str]) -> tuple[str, ...]: ...
    def delete(self, paths: Iterable[str], *, origin: ActionOrigin = ..., clear_asset_selection: bool = ...) -> tuple[str, ...]: ...
    def transfer_to_directory(self, paths: Iterable[str], destination: str, *, cut: bool, description: str = ..., origin: ActionOrigin = ..., select_results: bool = ...) -> tuple[str, ...]: ...
    def import_external(self, paths: Iterable[str], destination: str, *, origin: ActionOrigin = ..., select_results: bool = ...) -> tuple[str, ...]: ...
    def can_import_external(self, paths: Iterable[str], destination: str) -> bool: ...
    def move(self, source_path: str, destination_path: str, *, overwrite: bool = ..., origin: ActionOrigin = ..., select_result: bool = ...) -> str: ...
    def copy(self, source_path: str, destination_path: str, *, overwrite: bool = ..., origin: ActionOrigin = ..., select_result: bool = ...) -> str: ...
    def shutdown(self) -> None: ...

class ProjectAssetInteractionService:
    def __init__(self, assets: ProjectAssetCommandService, clipboard: Any) -> None: ...
    @property
    def configured(self) -> bool: ...
    def configure(self, *, unique_name: Callable[[str, str, str], str], create: Callable[[str, str, str, str], Any], open_asset: Callable[[str, str], bool], reveal: Callable[[str], bool], read_external_clipboard: Callable[[], Iterable[str]], request_delete: Callable[[tuple[str, ...], Callable[[list[str]], bool]], bool]) -> None: ...
    def can_copy(self, paths: Iterable[str]) -> bool: ...
    def copy(self, paths: Iterable[str], *, cut: bool) -> bool: ...
    def can_paste(self, destination: str) -> bool: ...
    def paste(self, destination: str, *, origin: ActionOrigin = ...) -> tuple[str, ...]: ...
    def transfer(self, paths: Iterable[str], destination: str, *, origin: ActionOrigin = ...) -> tuple[str, ...]: ...
    def request_delete(self, paths: Iterable[str], *, origin: ActionOrigin = ...) -> bool: ...
    def can_create(self, kind: str, directory: str, base_name: str, extension: str) -> bool: ...
    def create(self, kind: str, directory: str, base_name: str, extension: str, variant: str = ..., *, origin: ActionOrigin = ...) -> str: ...
    def can_open(self, kind: str, path: str) -> bool: ...
    def open(self, kind: str, path: str) -> bool: ...
    def reveal(self, path: str) -> bool: ...
    def shutdown(self) -> None: ...
