from typing import Any, Callable, Optional

BUILD_SETTINGS_DEFAULTS: dict[str, Any]

def normalize_build_settings(value: Any, *, project_path: Optional[str] = ...) -> dict[str, Any]: ...

class ProjectSettingsDocumentController:
    project_path: str
    settings_path: str
    document_id: str
    def __init__(self, project_path: str, *, tag_layer_manager: Any = ..., physics_module: Any = ..., submitter: Callable[..., Any] = ...) -> None: ...
    def add_listener(self, callback: Callable[[dict[str, Any]], None]) -> None: ...
    def remove_listener(self, callback: Callable[[dict[str, Any]], None]) -> None: ...
    def capture_document(self) -> dict[str, Any]: ...
    def section(self, name: str) -> dict[str, Any]: ...
    def restore_document(self, document: dict[str, Any], revision: Optional[int], *, persist: bool = ...) -> None: ...
    def apply_document(self, document: dict[str, Any], *, edit_key: str, description: str, view_id: str = ...) -> bool: ...
    def apply_section(self, name: str, value: dict[str, Any], *, edit_key: str, description: str, view_id: str = ...) -> bool: ...
    def apply_derived_section(self, name: str, value: dict[str, Any]) -> bool: ...
    def schedule_autosave(self, *, sections: Optional[tuple[str, ...]] = ...) -> bool: ...
    def poll_pending_writes(self) -> int: ...
    def save(self, *, ticket: Any, save_as: bool = ...) -> Any: ...
    def poll_save(self, ticket: Any) -> Optional[bool]: ...
    def discard(self, *, document_id: str) -> Any: ...
    def reload_from_resource(self, *, document_id: str, resource_path: str = ...) -> Any: ...

def ensure_project_settings_document(project_path: str, *, view_id: str = ..., tag_layer_manager: Any = ..., physics_module: Any = ...) -> ProjectSettingsDocumentController: ...
