from typing import Any, Optional
from .action_journal import ActionOrigin
from .commands import CommandSource

class RenderStackCommandService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> Optional[RenderStackCommandService]: ...
    def shutdown(self) -> None: ...
    def register_commands(self, registry: Any) -> None: ...
    def set_pipeline(self, stack: Any, pipeline_name: str, *, origin: ActionOrigin = ...) -> bool: ...
    def set_pipeline_parameter(self, stack: Any, field_name: str, value: Any, *, origin: ActionOrigin = ..., description: str = ..., old_value: Any = ...) -> bool: ...
    def set_effect_stage_slots(self, stack: Any, stage_id: str, slots: Any, *, origin: ActionOrigin = ..., description: str = ...) -> bool: ...

def submit_renderstack_command(command_id: str, *, source: CommandSource | str | None = ..., **payload: Any) -> bool: ...
