from typing import Any, Callable
from .documents import DocumentKind

class EditableResourceDocumentController:
    autosave_on_close: bool
    category: str
    file_path: str
    resource: Any
    document_id: str
    exec_layer: Any
    state: Any
    autosave_debounce_sec: float
    on_restored: Callable[[Any], None] | None
    def __init__(self, category: str, file_path: str, resource: Any, *, autosave_debounce_sec: float = ..., on_restored: Callable[[Any], None] | None = ...) -> None: ...
    def capture_document(self) -> dict: ...
    def bind(self, *, file_path: str, resource: Any, exec_layer: Any, state: Any) -> None: ...
    def restore_document(self, document: dict, revision: int | None, *, persist: bool = ...) -> None: ...
    def schedule_autosave(self) -> None: ...
    def apply_document(self, document: dict, *, view_id: str, edit_key: str, description: str, origin: Any = ...) -> bool: ...
    def commit_applied_document(self, old_document: dict, document: dict, *, view_id: str, edit_key: str, description: str, origin: Any = ...) -> bool: ...
    def poll_pending_writes(self) -> int: ...
    def poll_save(self, ticket: Any) -> bool | None: ...
    def flush_autosave(self, *, force: bool = ...) -> bool: ...
    def save(self, *, ticket: Any, save_as: bool = ...) -> Any: ...
    def discard(self, *, document_id: str) -> bool: ...
    def resource_moved(self, *, document_id: str, source_path: str, destination_path: str, guid: str) -> None: ...

def ensure_editable_resource_document(*, category: str, document_kind: DocumentKind, file_path: str, resource: Any, guid: str = ..., title: str = ..., view_id: str = ..., state: Any = ..., exec_layer: Any = ..., autosave_debounce_sec: float = ..., on_restored: Callable[[Any], None] | None = ...) -> EditableResourceDocumentController: ...
