from typing import Any, Callable, ContextManager

from .commands import CommandContext
from .clipboard import ClipboardService
from .selection import SelectionService
from .action_journal import ActionOrigin

class SceneObjectCommandService:
    def __init__(self, selection: SelectionService, clipboard: ClipboardService) -> None: ...
    def set_change_publisher(self, publisher: Callable[[], None] | None) -> None: ...
    def user_action(self, description: str) -> ContextManager[None]: ...
    @staticmethod
    def environment_command(old_values: Any, new_values: Any, description: str = ...) -> Any: ...
    def set_environment(self, changes: Any, *, description: str = ..., origin: ActionOrigin = ...) -> bool: ...
    @staticmethod
    def has_selection(context: CommandContext) -> bool: ...
    def can_copy(self, context: CommandContext) -> bool: ...
    def copy(self, context: CommandContext, *, cut: bool) -> bool: ...
    def duplicate(self, context: CommandContext) -> bool: ...
    def can_paste(self, context: CommandContext) -> bool: ...
    def paste(self, context: CommandContext) -> bool: ...
    def can_external_drop(self, reference: str, parent_id: int = 0, is_guid: bool = False) -> bool: ...
    def instantiate_prefab(self, reference: str, parent_id: int = 0, is_guid: bool = False) -> bool: ...
    def instantiate_prefab_object(self, reference: str, parent_id: int = 0, is_guid: bool = False) -> Any: ...
    def create_model(self, reference: str, parent_id: int = 0, is_guid: bool = False) -> bool: ...
    def create_model_object(self, reference: str, *, parent_id: int = ..., is_guid: bool = ..., name: str = ..., select: bool = ..., selection_owner_id: str = ..., selection_reason: str = ...) -> Any: ...
    def delete(self, context: CommandContext) -> bool: ...
    def delete_ids(self, object_ids: Any, *, description: str = ...) -> bool: ...
    def duplicate_object(self, object_id: int, *, parent_id: int = ..., name: str = ..., select: bool = ..., selection_owner_id: str = ..., selection_reason: str = ...) -> Any: ...
    def rename(self, object_id: int, new_name: str) -> bool: ...
    def can_set_object_property(self, object_id: int, property_name: str, value: Any) -> bool: ...
    def set_object_property(self, object_id: int, property_name: str, value: Any) -> bool: ...
    def can_set_transforms(self, object_ids: Any, transform_values: Any) -> bool: ...
    def set_transforms(self, object_ids: Any, transform_values: Any) -> bool: ...
    def move_hierarchy(self, object_ids: Any, mode: str, target_id: int = 0, after: bool = False) -> bool: ...
    def set_sibling_index(self, object_id: int, index: int) -> bool: ...
    def copy_selected(self, cut: bool = False) -> bool: ...
    def paste_clipboard(self) -> bool: ...
    def delete_selected(self) -> bool: ...
    def has_clipboard_data(self) -> bool: ...
