from typing import Any

def normalize_search_text(value: Any) -> str: ...

class SearchToken:
    query_revision: int
    source_generation: int
    scope_key: str
    def __init__(self, query_revision: int, source_generation: int = ..., scope_key: str = ...) -> None: ...

class SearchQueryModel:
    def __init__(self, query: str = ...) -> None: ...
    @property
    def query(self) -> str: ...
    @property
    def normalized_query(self) -> str: ...
    @property
    def revision(self) -> int: ...
    @property
    def active(self) -> bool: ...
    def set_query(self, value: Any) -> bool: ...
    def clear(self) -> bool: ...
    def matches(self, value: Any) -> bool: ...
    def matches_normalized(self, value: str) -> bool: ...
    def token(self, source_generation: int = ..., scope_key: str = ...) -> SearchToken: ...
    def accepts(self, token: SearchToken, source_generation: int = ..., scope_key: str = ...) -> bool: ...
