from typing import Callable, Iterable, Optional, Sequence
from .descriptors import SelectionDomain, SelectionSnapshot, SelectionTarget

class SelectionChange:
    before: SelectionSnapshot
    after: SelectionSnapshot
    reason: str
    record_history: bool

class SelectionService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> SelectionService: ...
    @classmethod
    def install(cls, service: SelectionService) -> None: ...
    @property
    def snapshot(self) -> SelectionSnapshot: ...
    @property
    def revision(self) -> int: ...
    def add_listener(self, callback: Callable[[SelectionChange], None]) -> None: ...
    def remove_listener(self, callback: Callable[[SelectionChange], None]) -> None: ...
    @staticmethod
    def reconciled_snapshot(snapshot: SelectionSnapshot, is_valid: Callable[[SelectionTarget], bool], *, fallback: Optional[SelectionTarget] = ..., fallback_owner_id: str = ...) -> SelectionSnapshot: ...
    def reconcile(self, is_valid: Callable[[SelectionTarget], bool], *, fallback: Optional[SelectionTarget] = ..., fallback_owner_id: str = ..., reason: str = ..., record_history: bool = ...) -> bool: ...
    def set_owner_domain_validator(self, validator: Optional[Callable[[str, SelectionDomain], bool]]) -> None: ...
    def scene_object_ids(self) -> tuple[int, ...]: ...
    def primary_scene_object_id(self) -> int: ...
    def is_scene_object_selected(self, object_id: int) -> bool: ...
    def set_ordered_scene_objects(self, owner_id: str, object_ids: Sequence[int]) -> None: ...
    def select_scene_object(self, object_id: int, *, owner_id: str, reason: str = "select_scene_object", record_history: bool = True) -> bool: ...
    def toggle_scene_object(self, object_id: int, *, owner_id: str, reason: str = "toggle_scene_object", record_history: bool = True) -> bool: ...
    def range_select_scene_object(self, object_id: int, *, owner_id: str, reason: str = "range_select_scene_object", record_history: bool = True) -> bool: ...
    def replace_scene_objects(self, object_ids: Iterable[int], *, owner_id: str, primary_object_id: int = 0, anchor_object_id: int = 0, reason: str = "replace_scene_objects", record_history: bool = True) -> bool: ...
    def box_select_scene_objects(self, object_ids: Iterable[int], *, additive: bool, owner_id: str, reason: str = "box_select_scene_objects", record_history: bool = True) -> bool: ...
    def set_ordered_targets(self, owner_id: str, targets: Sequence[SelectionTarget]) -> None: ...
    def replace(self, targets: Iterable[SelectionTarget], *, owner_id: str, primary: SelectionTarget | None = None, anchor: SelectionTarget | None = None, reason: str = "replace", record_history: bool = True) -> bool: ...
    def select(self, target: SelectionTarget, *, owner_id: str, reason: str = "select", record_history: bool = True) -> bool: ...
    def toggle(self, target: SelectionTarget, *, owner_id: str, reason: str = "toggle", record_history: bool = True) -> bool: ...
    def range_select(self, target: SelectionTarget, *, owner_id: str, reason: str = "range_select", record_history: bool = True) -> bool: ...
    def clear(self, *, reason: str = "clear", record_history: bool = True) -> bool: ...
    def apply_snapshot(self, snapshot: SelectionSnapshot, *, reason: str = "restore", record_history: bool = False) -> bool: ...
    def remap_asset_path(self, source_path: str, destination_path: str, *, reason: str = "asset_moved") -> bool: ...
