class EditorTransaction:
    description: str
    transaction_id: str
    def __init__(self, description: str, transaction_id: str = "") -> None: ...
    @property
    def command_count(self) -> int: ...
    @property
    def is_closed(self) -> bool: ...
    def execute(self, command: object) -> None: ...
    def record_applied(self, command: object) -> None: ...
    def rollback(self) -> None: ...
    def commit(self) -> object | None: ...
