from collections.abc import Callable
from typing import Optional

from .contexts import FocusService, FocusSnapshot

class TransientInteraction:
    token_id: str
    owner_id: str
    kind: str
    priority: int
    sequence: int

class TransientInteractionService:
    CONTEXT_ID: str
    def __init__(self, focus: Optional[FocusService] = ...) -> None: ...
    @classmethod
    def instance(cls) -> TransientInteractionService: ...
    @property
    def revision(self) -> int: ...
    @property
    def active(self) -> Optional[TransientInteraction]: ...
    @property
    def can_cancel(self) -> bool: ...
    def persistent_focus_snapshot(self, snapshot: Optional[FocusSnapshot] = ...) -> FocusSnapshot: ...
    def begin(self, owner_id: str, cancel: Callable[[], object], *, kind: str, priority: int = ..., token_id: str = ...) -> str: ...
    def end(self, token_id: str) -> bool: ...
    def cancel_active(self) -> bool: ...
    def cancel_owner(self, owner_id: str) -> int: ...
    def refresh_context(self) -> None: ...
    def clear(self) -> None: ...
