from collections.abc import Callable, Hashable, Iterable
from typing import Any, Optional
from .view_commands import ViewCommandService

class TreeViewStateService:
    def __init__(self, view_commands: ViewCommandService) -> None: ...
    @classmethod
    def instance(cls) -> Optional[TreeViewStateService]: ...
    @classmethod
    def require(cls) -> TreeViewStateService: ...
    def set_expanded(self, current_ids: Iterable[Hashable], item_id: Hashable, expanded: bool, apply: Callable[[list[Hashable]], Any], *, description: str) -> bool: ...
    def reveal_path(self, current_ids: Iterable[Hashable], path_ids: Iterable[Hashable], apply: Callable[[list[Hashable]], Any], *, description: str, record_history: bool = ...) -> bool: ...
    def shutdown(self) -> None: ...
