from collections.abc import Callable
from typing import Any, Optional

class ViewCommandService:
    def __init__(self) -> None: ...
    @classmethod
    def instance(cls) -> Optional[ViewCommandService]: ...
    @classmethod
    def require(cls) -> ViewCommandService: ...
    def set_value(self, old_value: Any, new_value: Any, apply: Callable[[Any], Any], *, description: str, owner_view_id: str = "") -> bool: ...
    def shutdown(self) -> None: ...
