from os import PathLike
from typing import Any

class Application:
    @staticmethod
    def is_editor() -> bool: ...
    @staticmethod
    def is_player() -> bool: ...
    @staticmethod
    def data_path() -> str: ...
    @staticmethod
    def persistent_data_path() -> str: ...
    @staticmethod
    def asset_path(path: str) -> str: ...
    @staticmethod
    def package_path(package_reference: str, relative_path: str | PathLike[str]) -> str: ...
    @staticmethod
    def open_url(target: str) -> bool: ...
    @staticmethod
    def renderer_state() -> dict[str, Any]: ...
    @staticmethod
    def quit(exit_code: int = 0) -> bool: ...
