from typing import Any, Callable, ContextManager, Literal, TypeVar
from numpy import ndarray

_F = TypeVar("_F", bound=Callable[..., Any])

class ComputeCapabilityError(RuntimeError): ...
class ComputeCompilerError(RuntimeError): ...
class KernelCompilationError(TypeError): ...
class ComputeExecutionError(RuntimeError): ...

class BufferDescription:
    shape: tuple[int, ...]
    dtype: str
    scalar_dtype: str
    lanes: int
    attribute_offsets: tuple[int, ...]
    capacity: int
    element_stride: int
    byte_offset: int
    byte_length: int
    nbytes: int
    device: Literal["cpu", "gpu"]
    usage: tuple[str, ...]
    access: Literal["read_write", "read_only"]
    ownership: Literal["owned", "borrowed"]
    generation: int
    resource_index: int | None
    resource_generation: int | None

class Statistics:
    submission_count: int
    dispatch_count: int
    upload_request_count: int
    upload_bytes: int
    readback_request_count: int
    readback_bytes: int
    staging_allocation_count: int
    host_map_count: int
    native_boundary_count: int
    wait_count: int
    cpu_submit_ms: float
    wait_ms: float
    pending_submission_count: int
    gpu_profile_available: bool
    gpu_profile_serial: int
    gpu_time_ms: float | None

class Buffer:
    def __init__(self, *, shape: int | tuple[int, ...], dtype: Any = ..., device: Literal["cpu", "gpu"], data: Any = ...) -> None: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> Literal["cpu", "gpu"]: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def element_count(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def readonly(self) -> bool: ...
    @property
    def description(self) -> BufferDescription: ...
    def set_data(self, data: Any, *, offset: int = ...) -> None:
        """Write elements; GPU uploads are ordered before later compute without a forced wait."""
        ...
    def get_data(self, out: Buffer | None = ..., *, offset: int = ..., count: int | None = ...) -> Buffer: ...
    def get_data_async(self, *, offset: int = ..., count: int | None = ...) -> Readback: ...
    def fill(self, value: Any) -> None: ...
    def zero(self) -> None: ...
    def numpy(self, *, copy: bool = ...) -> ndarray: ...
    def view(self, *, offset: int = ..., count: int | None = ..., readonly: bool = ...) -> Buffer: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: Any) -> Any: ...
    def __setitem__(self, index: Any, value: Any) -> None: ...
    def __enter__(self) -> Buffer: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class Readback:
    @property
    def done(self) -> bool: ...
    def get_data(self, out: Buffer | None = ...) -> Buffer: ...

class TransformBinding:
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...

class TransformPose:
    position: tuple[float, float, float]
    rotation: tuple[float, float, float, float]
    scale: tuple[float, float, float]

def buffer(*, shape: int | tuple[int, ...], dtype: Any = ..., device: Literal["cpu", "gpu"], data: Any = ...) -> Buffer: ...
def bind_transform(owner: Any, *, pose: Buffer, initial_pose: TransformPose | None = ..., domain: Buffer | None = ..., points: tuple[Buffer, ...] = ..., vectors: tuple[Buffer, ...] = ..., on_transform: Callable[[TransformPose, TransformPose], None] | None = ...) -> TransformBinding:
    """Bind a simulation pose; initial_pose makes the authored Transform initialize it immediately."""
    ...
def statistics(*, reset: bool = ...) -> Statistics: ...
def set_profiling_enabled(enabled: bool) -> None: ...

class Kernel:
    @property
    def function(self) -> Callable[..., Any]: ...

class Function:
    @property
    def function(self) -> Callable[..., Any]: ...

def kernel(function: _F) -> Kernel: ...
def function(function: _F) -> Function: ...
def index(domain: Buffer) -> int: ...
def atomic_add(target: Any, value: Any) -> Any: ...
def prepare(declaration: Kernel, params: tuple[Any, ...]) -> None:
    """Compile one specialization and create its pipelines without dispatching it."""
    ...
def launch(declaration: Kernel, params: tuple[Any, ...]) -> None: ...
def recording() -> ContextManager[None]:
    """Record ordered GPU launches into one submission until scope exit."""
    ...

__all__: list[str]
