from .engine.interaction.commands import (
    CommandContext as CommandContext,
    CommandResult as CommandResult,
    CommandSource as CommandSource,
    CommandStatus as CommandStatus,
    EditorCommand as EditorCommand,
    EditorCommandRegistry as EditorCommandRegistry,
)
from .engine.interaction.shortcuts import (
    KeyChord as KeyChord,
    ShortcutBinding as ShortcutBinding,
    ShortcutModifier as ShortcutModifier,
    ShortcutPhase as ShortcutPhase,
    ShortcutRouter as ShortcutRouter,
    ShortcutScope as ShortcutScope,
)

__all__: tuple[str, ...]

from typing import Callable, ContextManager
from os import PathLike
from .lib import GameObject
from .core.data_asset import DataAsset
from .engine.interaction.documents import (
    DocumentActionResult as DocumentActionResult,
    DocumentActionStatus as DocumentActionStatus,
)

def edit_scene(description: str) -> ContextManager[None]: ...
def create_game_object(name: str = ..., *, kind: str = ..., parent: GameObject | None = ..., configure: Callable[[GameObject], None] | None = ...) -> GameObject: ...
def create_prefab(game_object: GameObject, directory: str | PathLike[str] = ...) -> str: ...
def add_component(game_object: GameObject, type_name: str, *, configure: Callable[[object], None] | None = ...) -> object: ...
def create_data_asset(value: DataAsset, path: str | PathLike[str]) -> str: ...
def load_data_asset(path: str | PathLike[str]) -> DataAsset: ...
def set_data_asset_fields(asset: DataAsset, **values: object) -> bool: ...
def save_data_asset(asset: DataAsset) -> DocumentActionResult: ...
def create_folder(path: str | PathLike[str]) -> str: ...
def get_build_scenes() -> list[str]: ...
def set_build_scenes(paths: list[str | PathLike[str]] | tuple[str | PathLike[str], ...]) -> bool: ...
def save_project_settings() -> DocumentActionResult: ...
def instantiate_prefab(path: str | PathLike[str], *, parent: GameObject | None = ...) -> GameObject: ...
def apply_prefab(game_object: GameObject) -> bool: ...
def revert_prefab(game_object: GameObject) -> bool: ...
def revert_property_override(component: object, field_name: str) -> bool: ...
def save_scene(path: str | PathLike[str] | None = ...) -> DocumentActionResult: ...
def open_scene(path: str | PathLike[str]) -> bool: ...
def new_scene() -> None: ...
def undo(*, defer: bool = ...) -> None: ...
def redo(*, defer: bool = ...) -> None: ...
