from typing import Any, Mapping

class FieldSchema:
    property_path: str
    value_type: str
    read_only: bool
    attributes: Mapping[str, Any]
    def __init__(self, property_path: str, value_type: str, read_only: bool = False, attributes: Mapping[str, Any] = ...) -> None: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> FieldSchema: ...
    def to_document(self) -> dict[str, Any]: ...
    @classmethod
    def from_document(cls, document: Mapping[str, Any]) -> FieldSchema: ...

def get_native_field_schema(type_guid: str, field_id: str) -> FieldSchema: ...
