"""Authoritative Python filesystem path operations."""

from __future__ import annotations

import os
from typing import TypeAlias

PathLike: TypeAlias = str | os.PathLike[str]


def safe_path(path: PathLike) -> str:
    """Normalize a Python path before crossing the UTF-8 C++ boundary."""
    ...


def lexical_path(path: PathLike) -> str: ...
def resolved_path(path: PathLike) -> str: ...
def resolve_destination_path(path: PathLike) -> str: ...
def resolve_project_path(path: PathLike, root: PathLike) -> str: ...
def path_key(path: PathLike) -> str: ...
def lexical_path_key(path: PathLike) -> str: ...
def same_path(left: PathLike, right: PathLike) -> bool: ...
def is_case_only_rename(left: PathLike, right: PathLike) -> bool: ...
def is_path_within(path: PathLike, root: PathLike, *, allow_root: bool = ...) -> bool: ...
def relative_path(
    path: PathLike,
    root: PathLike,
    *,
    resolve: bool = ...,
    allow_root: bool = ...,
    allow_outside: bool = ...,
) -> str: ...
def portable_path(path: PathLike) -> str: ...
def portable_relative_path(path: PathLike, *, allow_root: bool = ...) -> str: ...
