from __future__ import annotations

from typing import Any, Optional

from infernux.engine.player_service_graph import PlayerRuntimeAssetCatalog


class PlayerSceneService:
    def __init__(self, *, asset_database: Any = None, native_engine: Any = None) -> None: ...
    @property
    def active_scene_path(self) -> Optional[str]: ...
    @property
    def is_load_pending(self) -> bool: ...
    @property
    def is_prepared(self) -> bool: ...
    @property
    def last_error(self) -> str: ...
    def bind_runtime_catalog(self, runtime_catalog: PlayerRuntimeAssetCatalog) -> None: ...
    def set_active_scene(self, scene: Any) -> None: ...
    def unload_scene(self, scene: Any) -> None: ...
    def load_initial(self, path: str, *, on_tick: Any = ...) -> bool: ...
    def request_load(self, path: str, *, mode: Any = ...) -> bool: ...
    def request_prepared_load(
        self, path: str, *, mode: Any = ..., hold_for_activation: bool = ...
    ) -> bool: ...
    def activate_prepared_load(self) -> bool: ...
    def process_pending_load(self) -> None: ...
    def cancel_pending_load(self) -> None: ...
