from __future__ import annotations

from typing import Any, Optional

from Infernux.engine.player_service_graph import (
    PlayerRuntimeAssetCatalog,
    RuntimeProductManifest,
)


class PlayerRuntimeSession:
    def __init__(
        self,
        *,
        asset_database: Any = None,
        native_engine: Any = None,
        scheduler: Any = None,
        scene_service: Any = None,
    ) -> None: ...
    @property
    def is_playing(self) -> bool: ...
    @property
    def is_paused(self) -> bool: ...
    @property
    def state(self) -> str: ...
    @property
    def active_scene_path(self) -> Optional[str]: ...
    @property
    def last_scene_error(self) -> str: ...
    @property
    def execution_scheduler(self) -> Any: ...
    def get_asset_database(self) -> Any: ...
    @property
    def runtime_manifest(self) -> Optional[RuntimeProductManifest]: ...
    def configure_runtime_contract(
        self,
        runtime_manifest: RuntimeProductManifest,
        runtime_catalog: PlayerRuntimeAssetCatalog,
    ) -> None: ...
    def load_scene(self, path: str) -> bool: ...
    def activate(self) -> bool: ...
    def tick(self, external_delta_time: Optional[float] = None) -> float: ...
    def shutdown(self) -> None: ...
