from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping, Sequence
from os import PathLike
from typing import Any

RUNTIME_BASELINE_SCHEMA_ID: str
RUNTIME_BASELINE_REPORT_SCHEMA_ID: str
RUNTIME_BASELINE_COMPONENT_COUNTS: tuple[int, ...]
RUNTIME_BASELINE_LIFECYCLE_CALLBACKS: tuple[str, ...]
RUNTIME_BASELINE_MUTATION_DOMAINS: tuple[str, ...]
RUNTIME_BASELINE_WORKLOADS: tuple[str, ...]
RUNTIME_BASELINE_SCENARIO_GROUPS: dict[str, tuple[str, ...]]
RUNTIME_BASELINE_SCENARIOS: tuple[str, ...]
RUNTIME_BASELINE_TIMING_FIELDS: tuple[str, ...]
RUNTIME_BASELINE_COUNTERS: tuple[str, ...]

class RuntimeBaselineIdentity:
    build_configuration: str
    application_role: str
    runtime_mode: str
    flavor: str
    platform: str
    architecture: str
    python_version: str
    native_profile_enabled: bool
    engine_version: str
    build_preset: str
    def __init__(self, build_configuration: str, application_role: str, runtime_mode: str, flavor: str, platform: str, architecture: str, python_version: str, native_profile_enabled: bool, engine_version: str = ..., build_preset: str = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class RuntimeWorkloadRequest:
    workload: str
    component_count: int
    repeat_index: int

class RuntimeScenarioRequest:
    scenario: str
    group: str
    repeat_index: int

class RuntimeBaselineRecorder:
    def __init__(self, identity: RuntimeBaselineIdentity, *, suite_id: str = ..., project_id: str = ..., capture_id: str | None = ..., created_utc: str | None = ...) -> None: ...
    @property
    def identity(self) -> RuntimeBaselineIdentity: ...
    def record_lifecycle_event(self, *, frame: int, callback: str, phase: str = ..., object_id: int | str = ..., component_id: int | str = ..., type_id: str = ..., details: Mapping[str, Any] | None = ...) -> None: ...
    def record_mutation_visibility(self, *, frame: int, domain: str, mutation_phase: str, observed_phase: str, visible_same_frame: bool, stable_id: int | str = ..., field_id: int | str = ..., details: Mapping[str, Any] | None = ...) -> None: ...
    def record_workload(self, *, workload: str, component_count: int, samples_ms: Iterable[float] | None = ..., user_script_samples_ms: Iterable[float] | None = ..., engine_overhead_samples_ms: Iterable[float] | None = ..., timing: Mapping[str, Any] | None = ..., counters: Mapping[str, int | float] | None = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def record_performance_window(self, *, name: str, sample_count: int, cpu_sections: Mapping[str, Mapping[str, Any]], gpu_sections: Mapping[str, Mapping[str, Any]] | None = ..., counters: Mapping[str, int | float] | None = ..., first_frame: int = ..., last_frame: int = ..., dropped_sample_count: int = ..., metadata: Mapping[str, Any] | None = ...) -> None: ...
    def record_inventory(self, *, services: Iterable[Any] = ..., threads: Iterable[Any] = ..., watchers: Iterable[Any] = ..., python_modules: Iterable[Any] = ..., native_modules: Iterable[Any] = ...) -> None: ...
    def add_diagnostic(self, code: str, message: str, *, severity: str = ..., details: Mapping[str, Any] | None = ...) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
    def summary(self) -> dict[str, Any]: ...
    def to_json(self, *, indent: int | None = ...) -> str: ...
    def write_json(self, path: str | PathLike[str]) -> str: ...

class RuntimeBaselineRunner:
    recorder: RuntimeBaselineRecorder
    def __init__(self, recorder: RuntimeBaselineRecorder) -> None: ...
    @classmethod
    def for_engine(cls, engine: Any, *, suite_id: str = ..., project_id: str = ..., build_configuration: str | None = ..., build_preset: str | None = ..., new_capture: bool = ...) -> RuntimeBaselineRunner: ...
    def run_workload_matrix(self, executor: Callable[[RuntimeWorkloadRequest], Mapping[str, Any] | float], *, workloads: Sequence[str] = ..., component_counts: Sequence[int] = ..., repeats: int = ...) -> list[dict[str, Any]]: ...
    def run_scenario_matrix(self, executor: Callable[[RuntimeScenarioRequest], Mapping[str, Any]], *, scenarios: Sequence[str] = ..., repeats: int = ...) -> list[dict[str, Any]]: ...
    def capture_native_performance_window(self, native_engine: Any, wait_frames: Callable[[int], Any], *, name: str, frames: int = ..., gpu_sections: Mapping[str, Mapping[str, Any]] | None = ..., counters: Mapping[str, int | float] | None = ..., metadata: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...
    def capture_runtime_inventory(self, engine: Any = ..., *, services: Iterable[Any] | None = ..., watchers: Iterable[Any] | None = ...) -> dict[str, Any]: ...
    def diagnostics(self, engine: Any = ...) -> dict[str, Any]: ...
    @staticmethod
    def compare(baseline: Mapping[str, Any], candidate: Mapping[str, Any], *, regression_threshold_percent: float = ...) -> dict[str, Any]: ...

def summarize_samples(values: Iterable[float]) -> dict[str, float | int]: ...
def detect_runtime_identity(engine: Any = ..., *, build_configuration: str | None = ..., application_role: str | None = ..., runtime_mode: str | None = ..., build_preset: str | None = ...) -> RuntimeBaselineIdentity: ...
def runtime_baseline_recorder(engine: Any, *, suite_id: str = ..., project_id: str = ..., build_configuration: str | None = ..., build_preset: str | None = ..., replace: bool = ...) -> RuntimeBaselineRecorder: ...
def collect_runtime_inventory(engine: Any = ..., *, services: Iterable[Any] | None = ..., watchers: Iterable[Any] | None = ...) -> dict[str, list[Any]]: ...
def runtime_baseline_diagnostics(engine: Any, *, recorder: RuntimeBaselineRecorder | None = ...) -> dict[str, Any]: ...
def compare_runtime_baselines(baseline: Mapping[str, Any], candidate: Mapping[str, Any], *, regression_threshold_percent: float = ...) -> dict[str, Any]: ...
def load_runtime_baseline(path: str | PathLike[str]) -> dict[str, Any]: ...
def write_runtime_baseline_comparison(baseline_path: str | PathLike[str], candidate_path: str | PathLike[str], output_path: str | PathLike[str], *, regression_threshold_percent: float = ...) -> str: ...
