from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
from typing import Iterable, Optional, Union

PathLike = Union[str, os.PathLike[str]]


class ScriptDependencyGraphError(ValueError): ...
class ModuleIdentityError(ScriptDependencyGraphError): ...
class StaleDependencyGraphTransaction(ScriptDependencyGraphError): ...
class DependencyGraphRollbackError(ScriptDependencyGraphError): ...


class DependencyKind(str, Enum):
    PROJECT: str
    EXTERNAL: str
    UNRESOLVED: str
    DYNAMIC: str


@dataclass(frozen=True, order=True)
class ModuleId:
    project_id: str
    module_name: str
    path_key: str


@dataclass(frozen=True)
class DependencyEdge:
    source: ModuleId
    imported_name: str
    target: Optional[ModuleId]
    kind: DependencyKind
    import_form: str
    line: int
    column: int
    external_name: str = ...
    external_origin: str = ...
    dynamic: bool = ...


@dataclass(frozen=True)
class ModuleRecord:
    id: ModuleId
    source_path: str
    is_package: bool
    source_hash: str
    revision: int
    dependencies: tuple[DependencyEdge, ...] = ...
    parse_error: str = ...


@dataclass(frozen=True)
class DependencyGraphSnapshot:
    revision: int
    modules: tuple[ModuleRecord, ...]
    edges: tuple[DependencyEdge, ...]


@dataclass(frozen=True)
class GraphMutation:
    operation: str
    revision: int
    changed: tuple[ModuleId, ...] = ...
    removed: tuple[ModuleId, ...] = ...
    affected: tuple[ModuleId, ...] = ...


class StagedDependencyGraphTransaction:
    """Immutable opaque candidate graph owned by one ScriptDependencyGraph."""
    @property
    def base_revision(self) -> int: ...
    @property
    def revision(self) -> int: ...
    @property
    def upserts(self) -> tuple[ModuleId, ...]: ...
    @property
    def removals(self) -> tuple[ModuleId, ...]: ...
    @property
    def mutation(self) -> GraphMutation: ...
    @property
    def affected(self) -> tuple[ModuleId, ...]: ...
    @property
    def strongly_connected_components(self) -> tuple[tuple[ModuleId, ...], ...]: ...
    @property
    def dependency_batches(self) -> tuple[tuple[ModuleId, ...], ...]: ...
    @property
    def ordered_modules(self) -> tuple[ModuleId, ...]: ...


class ScriptDependencyGraph:
    """Editor dependency graph over project ``Assets`` Python source files."""
    def __init__(self, project_root: PathLike, assets_root: Optional[PathLike] = ...) -> None: ...
    @property
    def project_root(self) -> str: ...
    @property
    def assets_root(self) -> str: ...
    @property
    def revision(self) -> int: ...
    def bind_owner_thread(self) -> None: ...
    def snapshot(self) -> DependencyGraphSnapshot: ...
    def index_assets(self) -> GraphMutation: ...
    def rebuild(self) -> GraphMutation: ...
    def stage_transaction(
        self,
        upserts: Mapping[PathLike, Optional[bytes | str]]
        | Iterable[PathLike | tuple[PathLike, Optional[bytes | str]]],
        removals: Iterable[PathLike | ModuleId | str] | PathLike | ModuleId | str = ...,
    ) -> StagedDependencyGraphTransaction: ...
    def commit_transaction(self, transaction: StagedDependencyGraphTransaction) -> GraphMutation: ...
    def rollback_transaction(self, transaction: StagedDependencyGraphTransaction) -> GraphMutation: ...
    def abort_transaction(self, transaction: StagedDependencyGraphTransaction) -> None: ...
    def upsert(self, path: PathLike, source: Optional[bytes | str] = ...) -> GraphMutation: ...
    def remove(self, path_or_module: PathLike | ModuleId) -> GraphMutation: ...
    def module_for_path(self, path: PathLike) -> Optional[ModuleRecord]: ...
    def module_for_name(self, module_name: str) -> Optional[ModuleRecord]: ...
    def resolve_module(self, module_name: str, *, from_module: Optional[ModuleId] = ..., level: int = ...) -> Optional[ModuleId]: ...
    def dependencies_of(self, selector: PathLike | ModuleId | str) -> tuple[DependencyEdge, ...]: ...
    def dependents_of(self, selector: PathLike | ModuleId | str) -> tuple[ModuleId, ...]: ...
    def external_dependencies(self, selector: Optional[PathLike | ModuleId | str] = ...) -> tuple[DependencyEdge, ...]: ...
    def affected_closure(self, changed: Iterable[PathLike | ModuleId | str] | PathLike | ModuleId | str) -> tuple[ModuleId, ...]: ...
    def strongly_connected_components(self) -> tuple[tuple[ModuleId, ...], ...]: ...


__all__: list[str]
