from __future__ import annotations

from enum import Enum
from typing import TypeAlias

Vector2: TypeAlias = tuple[float, float]
ActionValue: TypeAlias = float | Vector2

class InputActionType(str, Enum):
    BUTTON: InputActionType
    AXIS: InputActionType
    VECTOR2: InputActionType

class InputActionPhase(str, Enum):
    WAITING: InputActionPhase
    PERFORMED: InputActionPhase
    CANCELED: InputActionPhase

class InputAction:
    name: str
    action_type: InputActionType
    press_point: float
    @property
    def enabled(self) -> bool: ...
    @enabled.setter
    def enabled(self, value: bool) -> None: ...
    def __init__(self, name: str, action_type: InputActionType | str = ..., *, press_point: float = ...) -> None: ...
    def bind_key(self, key: str | int, *, scale: float = ...) -> InputAction: ...
    def bind_2d_composite(self, *, up: str | int, down: str | int, left: str | int, right: str | int, scale: float = ...) -> InputAction: ...
    def bind_pointer_delta(self, *, scale: float = ..., invert_y: bool = ...) -> InputAction: ...
    def set_virtual_value(self, source: str, value: ActionValue) -> None: ...
    def clear_virtual_value(self, source: str) -> None: ...
    def remove_virtual_source(self, source: str) -> None: ...
    def read_value(self) -> ActionValue: ...
    @property
    def is_pressed(self) -> bool: ...
    @property
    def was_pressed_this_frame(self) -> bool: ...
    @property
    def was_released_this_frame(self) -> bool: ...
    @property
    def phase(self) -> InputActionPhase: ...

class InputActionMap:
    name: str
    enabled: bool
    def __init__(self, name: str = ...) -> None: ...
    def add_action(self, name: str, action_type: InputActionType | str = ..., *, press_point: float = ...) -> InputAction: ...
    def find_action(self, name: str) -> InputAction | None: ...
    def __getitem__(self, name: str) -> InputAction: ...
    @property
    def actions(self) -> tuple[InputAction, ...]: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def remove_virtual_source(self, source: str) -> None: ...
    @classmethod
    def standard_gameplay(cls) -> InputActionMap: ...
