class ImeInputState:
    def __init__(self) -> None: ...
    def begin_composition(self, composition_id: str) -> None: ...
    def commit(self, text: str, *, composition_id: str = ..., commit_id: str = ...) -> str: ...
    def accept_key_down(self, key: str, *, event_id: str = ..., repeat: bool = ..., text_input_active: bool = ...) -> bool: ...
    def reset(self) -> None: ...
