"""Publish bilingual release history from the root changelogs and older releases.

The root Markdown is authoritative for authored notes. The checked-in historical
GitHub record preserves older releases that predate those files. No network is
needed to build or verify the site.
"""
from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"


def authored_notes(filename: str) -> dict[str, str]:
    source = (ROOT / filename).read_text(encoding="utf-8")
    blocks = re.split(r"(?=^# Infernux v\d)", source, flags=re.M)
    result = {}
    for block in blocks:
        if not block.strip():
            continue
        match = re.match(r"# Infernux v(\d+\.\d+\.\d+)\b", block)
        if not match or match[1] in result:
            raise ValueError(f"Invalid or duplicate release heading in {filename}")
        result[match[1]] = re.sub(r"\n---\s*$", "", block).strip()
    return result


def release_records() -> list[dict]:
    english = authored_notes("UpdateLog.md")
    chinese = authored_notes("UpdateLog-zh.md")
    if english.keys() != chinese.keys():
        raise ValueError("English and Chinese changelogs must cover the same versions")
    history = json.loads((DOCS / "changelog/history.json").read_text(encoding="utf-8"))
    records = {record["tag_name"][1:]: record for record in history}
    published = json.loads((DOCS / "release.json").read_text(encoding="utf-8"))
    if published.get("published_at"):
        version = published["version"]
        records.setdefault(version, {}).update(published_at=published["published_at"], html_url=published["release_url"])
    for version in english:
        record = records.setdefault(version, {})
        record.update(en=english[version], zh=chinese[version])
    return [dict(records[version], version=version) for version in sorted(
        records, key=lambda value: tuple(map(int, value.split("."))), reverse=True
    )]


def shell(title: str, description: str, route: str, body: str) -> str:
    # Reuse the maintained site chrome, including accessibility and CSP policy.
    base = (DOCS / "start.html").read_text(encoding="utf-8")
    head = base[:base.index("    <main")]
    foot = base[base.index('    <footer class="footer">'):]
    head = re.sub(r"<!--.*?-->\s*", "<!-- Generated by docs/tools/build-changelog.py. -->\n", head, count=1, flags=re.S)
    head = head.replace('data-title-i18n="pageTitle.start"', 'data-title-i18n="pageTitle.changelog"' if route == "changelog.html" else "")
    head = re.sub(r"<title>.*?</title>", f"<title>{html.escape(title)}</title>", head)
    head = re.sub(r'(?:name="(?:description|twitter:description)"|property="og:description") content="[^"]*"',
                  lambda m: m[0].split(" content=")[0] + f' content="{html.escape(description, quote=True)}"', head)
    head = re.sub(r'((?:property="og:title"|name="twitter:title") content=")[^"]*',
                  lambda m: m[1] + html.escape(title, quote=True), head)
    head = head.replace("https://infernux-engine.com/start.html", "https://infernux-engine.com/" + route)
    head = head.replace('class="active nav-priority" aria-current="page"', 'class="nav-priority"')
    head = head.replace('css/start.css?v=3', 'css/changelog.css?v=1')
    foot = foot.replace('js/i18n-start.js?v=2', 'js/i18n-changelog.js?v=1')
    if "/" in route:
        def relative(match):
            value = match[2]
            if re.match(r"(?:https?:|/|#|data:)", value):
                return match[0]
            return match[1] + '="../' + value + '"'
        head = re.sub(r'(href|src|data-href-en|data-href-zh)="([^"]+)"', relative, head)
        foot = re.sub(r'(href|src|data-href-en|data-href-zh)="([^"]+)"', relative, foot)
    return head + '    <main class="page-shell changelog-page" id="main-content">\n' + body + "\n    </main>\n\n" + foot


def status(record: dict, language: str) -> str:
    if record.get("published_at"):
        return record["published_at"][:10]
    return "Release in preparation" if language == "en" else "正在准备发布"


def content(record: dict, language: str) -> str:
    if language in record:
        source = record[language]
        source = re.sub(r"^# Infernux .+\n", "", source)
        source = re.sub(r"^\[.*\]\(UpdateLog(?:-zh)?\.md\)\s*$", "", source, flags=re.M)
        source = source.replace("### ", "## ")
    else:
        notice = "Original release notes (English)" if language == "en" else "以下保留原始发布记录（英文）"
        source = f"*{notice}*\n\n" + record["body"]
        source = re.sub(r'\]\((UpdateLog(?:-zh)?\.md)\)',
                        lambda match: f'](https://github.com/ChenlizheMe/Infernux/blob/v{record["version"]}/{match[1]})', source)
    rendered = markdown.markdown(source, extensions=["fenced_code", "tables", "toc"])
    # Both translations share one document; heading anchors must stay unique.
    return re.sub(r'\bid="([^"]+)"', lambda match: f'id="{language}-{match[1]}"', rendered)


def generate() -> dict[Path, str]:
    records = release_records()
    output = {}
    index = []
    for lang in ("en", "zh"):
        heading = "Built release by release." if lang == "en" else "记录引擎的每一次成长。"
        intro = ("New capabilities, fixes and upgrade notes. Read the complete history of Infernux, in English and Chinese."
                 if lang == "en" else "新能力、问题修复与升级须知。在这里查看 Infernux 每一期的完整变化。")
        index.append(f'<section class="container" data-page-language="{lang}"' + (" hidden" if lang == "zh" else "") + ">")
        index.append(f'<header class="changelog-heading"><span class="mini-tag">INFERNUX / RELEASES</span><h1>{heading}</h1><p>{intro}</p></header><ol class="release-list">')
        for record in records:
            version = record["version"]
            authored = record.get(lang, "")
            title = authored.split("\n", 1)[0].partition(" · ")[2] or ("Release notes" if lang == "en" else "发布记录")
            summary = next((part for part in authored.split("\n\n")[1:] if part.strip()),
                           "Original GitHub release notes, preserved as published." if lang == "en" else "保留当期 GitHub 原始发布记录。")
            summary = re.sub(r"[*`]", "", summary)
            featured = " release-featured" if record is records[0] else ""
            index.append(f'<li class="release-card{featured}"><div class="release-meta"><strong>v{version}</strong><span>{status(record, lang)}</span></div><h2><a href="changelog/{version}.html?lang={lang}">{html.escape(title)}</a></h2><p>{html.escape(summary)}</p><a class="release-read" href="changelog/{version}.html?lang={lang}">' + ("Read full changelog →" if lang == "en" else "阅读完整更新日志 →") + "</a></li>")
        index.append("</ol></section>")
    output[DOCS / "changelog.html"] = shell("Changelog · Infernux", "Every Infernux release: features, fixes and upgrade notes in English and Chinese.", "changelog.html", "\n".join(index))
    for record in records:
        version = record["version"]
        bodies = []
        for lang in ("en", "zh"):
            title = record.get(lang, "").split("\n", 1)[0].partition(" · ")[2] or ("Release notes" if lang == "en" else "发布记录")
            back = "← All releases" if lang == "en" else "← 全部版本"
            bodies.append(f'<article class="container release-article" data-page-language="{lang}"' + (" hidden" if lang == "zh" else "") + f'><a href="../roadmap.html#release-log">{back}</a><header class="changelog-heading"><span class="mini-tag">v{version} · {status(record, lang)}</span><h1>{html.escape(title)}</h1>')
            if record.get("published_at"):
                release_url = record.get("html_url", f"https://github.com/ChenlizheMe/Infernux/releases/tag/v{version}")
                bodies.append(f'<a href="{html.escape(release_url, quote=True)}">GitHub Release ↗</a>')
            bodies.append('</header><div class="release-prose">' + content(record, lang) + "</div></article>")
        output[DOCS / f"changelog/{version}.html"] = shell(f"Infernux {version} · Changelog", f"Infernux {version}: features, fixes and upgrade notes.", f"changelog/{version}.html", "\n".join(bodies))
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = generate()
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"Stale changelog page: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    print(f"{'Verified' if args.check else 'Generated'} {len(outputs)} bilingual changelog pages")


if __name__ == "__main__":
    main()
