"""ClosablePanel — base class for dockable ImGui windows.

Provides open/close state management, window-manager integration,
and focus tracking. Subclassed by :class:`EditorPanel`.
"""

from __future__ import annotations

from typing import Optional

from infernux.lib import InxGUIRenderable, InxGUIContext


class ClosablePanel(InxGUIRenderable):
    """A dockable ImGui window with open/close lifecycle."""

    WINDOW_TYPE_ID: Optional[str]
    WINDOW_DISPLAY_NAME: Optional[str]
    WINDOW_TITLE_KEY: Optional[str]

    def __init__(self, title: str, window_id: Optional[str] = None) -> None: ...

    @property
    def window_id(self) -> str:
        """Unique window identifier used by the window manager."""
        ...

    @property
    def panel_type_id(self) -> str: ...

    def set_panel_identity(self, panel_type_id: str, view_id: str) -> None: ...

    @property
    def is_open(self) -> bool:
        """Whether the panel is currently visible."""
        ...

    @property
    def document_id(self) -> str: ...

    def bind_document(
        self, document_id: str, *, replace_existing: bool = False
    ) -> None: ...
    def _bind_replaced_document(self, document_id: str, *, dirty: bool) -> None: ...
    def unbind_document(self) -> None: ...
    def retire_deleted_document(self, document_id: str) -> bool: ...
    def request_document_replacement(self, replace) -> bool: ...
    def request_document_resource_open(self, kind, path: str) -> bool: ...
    def capture_document_restore_state(self, document_id: str): ...
    def restore_document_restore_state(self, state) -> None: ...
    def restore_persisted_session_document(self) -> bool: ...
    def recover_incompatible_document_restore_state(self, state, error: Exception) -> bool: ...

    def set_window_manager(self, window_manager: object) -> None: ...

    def open(self) -> None:
        """Show the panel (registers with window manager if needed)."""
        ...

    def request_focus(self, ctx: InxGUIContext) -> None:
        """Request ImGui keyboard focus for this panel."""
        ...

    def current_child_context_id(self) -> str: ...
    def restore_child_context(self, context_id: str) -> bool: ...
    def publish_child_context(self, context_id: str, *, reason: str = ..., record_history: bool = ...) -> bool: ...

    @classmethod
    def get_active_panel_id(cls) -> Optional[str]:
        """Return the capability type of the currently focused panel."""
        ...

    @classmethod
    def get_active_view_id(cls) -> Optional[str]: ...

    @classmethod
    def focus_panel_by_id(cls, panel_id: str) -> None:
        """Programmatically focus a panel by its ``window_id``."""
        ...
