from __future__ import annotations

from infernux.engine.ui.editor_panel import FloatingEditorPanel


class EnvironmentSettingsPanel(FloatingEditorPanel):
    def __init__(self) -> None: ...
    def request_close(self) -> bool: ...
    def on_render_content(self, ctx: object) -> None: ...
