from __future__ import annotations

from enum import Enum
from typing import Iterable

class InspectorRevisionLayer(str, Enum):
    TARGET: InspectorRevisionLayer
    SCHEMA: InspectorRevisionLayer
    VALUE: InspectorRevisionLayer
    PREVIEW: InspectorRevisionLayer

class InspectorTarget:
    kind: str
    identity: str
    @classmethod
    def none(cls) -> InspectorTarget: ...
    @classmethod
    def scene_object(cls, object_id: int) -> InspectorTarget: ...
    @classmethod
    def asset(cls, path: str) -> InspectorTarget: ...

class InspectorRevisionSnapshot:
    target: InspectorTarget
    target_revision: int
    schema_revision: int
    value_revision: int
    preview_revision: int
    def token(self) -> tuple[int, int, int, int]: ...

class InspectorSnapshotService:
    @classmethod
    def instance(cls) -> InspectorSnapshotService: ...
    def set_active_target(self, target: InspectorTarget) -> int: ...
    def active_target(self) -> InspectorTarget: ...
    def revision(self) -> int: ...
    def consumed_journal_revision(self) -> int: ...
    def register_component(self, component, *, target: InspectorTarget | None = ...) -> int: ...
    def register_target_components(self, target: InspectorTarget, components: Iterable) -> None: ...
    def invalidate(self, layer: InspectorRevisionLayer, *, target: InspectorTarget | None = ..., component_id: int = ..., field_id: str = ..., domain: str = ...) -> int: ...
    def invalidate_target(self, target: InspectorTarget | None = ...) -> int: ...
    def invalidate_schema(self, target: InspectorTarget | None = ..., *, component_id: int = ..., domain: str = ...) -> int: ...
    def invalidate_value(self, target: InspectorTarget | None = ..., *, component_id: int = ..., field_id: str = ..., domain: str = ...) -> int: ...
    def invalidate_preview(self, target: InspectorTarget | None = ..., *, component_id: int = ..., domain: str = ...) -> int: ...
    def snapshot(self, target: InspectorTarget | None = ..., *, component_ids: Iterable[int] = ..., domains: Iterable[str] = ...) -> InspectorRevisionSnapshot: ...
    def aggregate(self, targets: Iterable[InspectorTarget]) -> InspectorRevisionSnapshot: ...
    def component_snapshot(self, component) -> InspectorRevisionSnapshot: ...
    def field_revision(self, component, field_id: str) -> int: ...
    def consume_changes(self, change_set) -> bool: ...
    def reset_for_tests(self) -> None: ...

def target_for_component(component) -> InspectorTarget: ...
def invalidate_component_field(component, field_id: str) -> int: ...
def invalidate_component_schema(component) -> int: ...
def refresh_visible_play_transforms(object_ids: Iterable[int], *, playing: bool) -> int: ...
def sync_selected_transforms_from_native_serial(
    serial: int,
    object_ids: Iterable[int],
    *,
    previous_serial: int | None,
) -> int: ...
def invalidate_scene_transforms(object_ids: Iterable[int]) -> int: ...
def invalidate_rebuilt_scene() -> int: ...
