from __future__ import annotations

from typing import Any


def prepare_component_icon_pixels(tex_data: Any) -> tuple[list[int], int, int]: ...
def bump_component_structure_version() -> None: ...
def get_component_structure_version() -> int: ...
def bump_inspector_value_generation(*, publish_snapshot: bool = ...) -> int: ...
def get_inspector_value_generation() -> int: ...
def invalidate_inspector_component_field(component, field_id: str) -> int: ...
def invalidate_inspector_preview(file_path: str, *, domain: str = ...) -> int: ...
def is_inspector_profile_enabled() -> bool: ...
def record_inspector_profile_timing(bucket: str, elapsed_ms: float) -> None: ...
def record_inspector_profile_count(bucket: str, amount: float = 1.0) -> None: ...
def consume_inspector_profile_metrics() -> dict[str, float]: ...
def ensure_material_file_path(material: Any) -> str: ...
