#version 450
layout(local_size_x = 8, local_size_y = 8) in;
layout(set = 0, binding = 0) uniform sampler2D sourceTexture;
layout(std430, set = 0, binding = 1) writeonly buffer Result { vec4 pixels[]; };
void main()
{
    ivec2 size = textureSize(sourceTexture, 0);
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(p, size))) return;
    pixels[p.y * size.x + p.x] = textureLod(sourceTexture, (vec2(p) + 0.5) / vec2(size), 0.0);
}
